Repository istio/installer, pull requests merged in 2019-08, with the labels that each got.

#303 Change to fit for container run as nonrun
  istio-control/istio-autoinject/templates/deployment.yaml
  istio-control/istio-autoinject/templates/service.yaml
  istio-control/istio-config/templates/deployment.yaml
  istio-control/istio-config/templates/service.yaml
  kustomize/istio-1.2/default/istio.yaml
  kustomize/istio-control/istio-config.yaml
  test/demo/k8s.yaml
Labels: cla: yes, size/M

#300 Set -discoveryAddress only once in injector template
  istio-control/istio-autoinject/files/injection-template.yaml
Labels: cla: yes, needs-ok-to-test, size/XS

#304 Jaeger to support badger
  istio-telemetry/tracing/templates/deployment-jaeger.yaml
  istio-telemetry/tracing/templates/pvc.yaml
  istio-telemetry/tracing/values.yaml
Labels: cla: yes, size/M

#307 Add context.proxy_version mixer attribute
  istio-policy/templates/config.yaml
  istio-telemetry/mixer-telemetry/templates/config.yaml
  kustomize/default/gen-istio-telemetry.yaml
  kustomize/istio-1.2/default/istio.yaml
  test/demo/k8s.yaml
Labels: cla: yes, size/S

#302 disable scrap endpoints that require certificate when prometheus.security=false
  istio-telemetry/prometheus-operator/templates/servicemonitors.yaml
  istio-telemetry/prometheus-operator/values.yaml
  istio-telemetry/prometheus/templates/configmap.yaml
  istio-telemetry/prometheus/values.yaml
Labels: cla: yes, size/S

#311 fix wrong helm variable name
  istio-telemetry/prometheus-operator/templates/servicemonitors.yaml
Labels: cla: yes, size/XS

#299 Mixer should use local useMCP var and Mixer's sidecar should be configurable
  istio-control/istio-discovery/values.yaml
  istio-telemetry/mixer-telemetry/templates/deployment.yaml
  istio-telemetry/mixer-telemetry/values.yaml
Labels: cla: yes, size/S

#315 Fix prom operator variable
  istio-telemetry/prometheus-operator/templates/servicemonitors.yaml
Labels: cla: yes, size/XS

#314 Fix telemetry labels
  istio-telemetry/mixer-telemetry/templates/deployment.yaml
  istio-telemetry/mixer-telemetry/templates/service.yaml
  kustomize/default/gen-istio-autoinject.yaml
  kustomize/default/gen-istio-citadel.yaml
  kustomize/default/gen-istio-config.yaml
  kustomize/default/gen-istio-discovery.yaml
  kustomize/default/gen-istio-grafana.yaml
  kustomize/default/gen-istio-ingress.yaml
  kustomize/default/gen-istio-prometheus.yaml
  kustomize/default/gen-istio-telemetry.yaml
  test/demo/k8s.yaml
Labels: cla: yes, size/M

#291 add configurable rolling update strategy.
  gateways/istio-egress/templates/deployment.yaml
  gateways/istio-egress/values.yaml
  gateways/istio-ingress/templates/deployment.yaml
  gateways/istio-ingress/values.yaml
  istio-control/istio-autoinject/templates/deployment.yaml
  istio-control/istio-autoinject/values.yaml
  istio-control/istio-config/templates/deployment.yaml
  istio-control/istio-config/values.yaml
  istio-control/istio-discovery/templates/deployment.yaml
  istio-control/istio-discovery/values.yaml
  istio-policy/templates/deployment.yaml
  istio-policy/values.yaml
  istio-telemetry/mixer-telemetry/templates/deployment.yaml
  istio-telemetry/mixer-telemetry/values.yaml
  istiocoredns/templates/deployment.yaml
  istiocoredns/values.yaml
  security/citadel/templates/deployment.yaml
  security/citadel/values.yaml
Labels: cla: yes, size/M

#313 Add missing pieces to the demo, and cleanup.
  istio-control/istio-config/templates/clusterrole.yaml
  istio-control/istio-config/templates/deployment.yaml
  istio-policy/templates/config.yaml
  test/demo/allocation.yaml
  test/demo/gen-egress.yaml
  test/demo/gen-grafana.yaml
  test/demo/gen-istio.yaml
  test/demo/gen-kiali.yaml
  test/demo/gen-policy.yaml
  test/demo/gen-prometheus.yaml
  test/demo/gen-tracing.yaml
  test/demo/kustomization.yaml
  test/demo/namespace.yaml
  test/demo/values.yaml
  test/install.mk
Labels: cla: yes, size/XXL

#317 Turn of Struct marshalling
  istio-control/istio-discovery/templates/deployment.yaml
Labels: cla: yes, size/XS

#320 fix telemetry values.
  istio-telemetry/mixer-telemetry/values.yaml
Labels: cla: yes, size/M

#318 Add Stackdriver tracing metrics and enable authentication methods
  istio-telemetry/mixer-telemetry/templates/stackdriver.yaml
  istio-telemetry/mixer-telemetry/values.yaml
Labels: cla: yes, size/M

#316 Sync changes to old installer
  gateways/istio-egress/templates/deployment.yaml
  gateways/istio-egress/values.yaml
  gateways/istio-ingress/templates/deployment.yaml
  gateways/istio-ingress/values.yaml
  global.yaml
  istio-control/istio-autoinject/files/injection-template.yaml
  istio-control/istio-autoinject/values.yaml
  istio-control/istio-config/values.yaml
  istio-control/istio-discovery/templates/configmap.yaml
  istio-control/istio-discovery/templates/deployment.yaml
  istio-control/istio-discovery/values.yaml
  istio-policy/templates/deployment.yaml
  istio-policy/values.yaml
  istio-telemetry/grafana/templates/deployment.yaml
  istio-telemetry/grafana/values.yaml
  istio-telemetry/kiali/templates/clusterrolebinding.yaml
  istio-telemetry/kiali/templates/deployment.yaml
  istio-telemetry/kiali/values.yaml
  istio-telemetry/mixer-telemetry/templates/config.yaml
  istio-telemetry/mixer-telemetry/templates/deployment.yaml
  istio-telemetry/mixer-telemetry/values.yaml
  istio-telemetry/prometheus-operator/values.yaml
  istio-telemetry/prometheus/templates/deployment.yaml
  istio-telemetry/prometheus/values.yaml
  istio-telemetry/tracing/templates/deployment-jaeger.yaml
  istio-telemetry/tracing/templates/deployment-zipkin.yaml
  istio-telemetry/tracing/values.yaml
  istiocoredns/values.yaml
  security/certmanager/templates/deployment.yaml
  security/certmanager/values.yaml
  security/citadel/templates/deployment.yaml
  security/citadel/values.yaml
  security/nodeagent/values.yaml
  test/demo/values.yaml
Labels: cla: yes, size/L

#324 Set release managers as CODEOWNERS for release-1.3
  CODEOWNERS
Labels: area/test and release, cla: yes, size/XS

#321 Make HPA name consistent for ingressgateway
  gateways/istio-ingress/templates/autoscale.yaml
Labels: cla: yes, size/XS

#325 Fix indentation for citadel service account
  security/citadel/templates/serviceaccount.yaml
Labels: cla: yes, size/S

#253 make all images configurable
  istio-cni/templates/daemonset.yaml
  istio-telemetry/prometheus-operator/templates/prometheus.yaml
Labels: cla: yes, size/XS

#329 fix error scale target reference in gateways hpa.
  gateways/istio-egress/templates/autoscale.yaml
  gateways/istio-ingress/templates/autoscale.yaml
Labels: action/merge-to-release-1.3-branch, cla: yes, size/XS

#328 add priority class for telemetry.
  istio-telemetry/mixer-telemetry/templates/deployment.yaml
Labels: action/merge-to-release-1.3-branch, cla: yes, size/XS

#326 Update grafana-dashboard for syncing with istio/istio install k8s
  istio-telemetry/grafana/dashboards/citadel-dashboard.json
  istio-telemetry/grafana/dashboards/galley-dashboard.json
  istio-telemetry/grafana/dashboards/istio-performance-dashboard.json
  istio-telemetry/grafana/dashboards/mixer-dashboard.json
  istio-telemetry/grafana/dashboards/pilot-dashboard.json
Labels: cla: yes, needs-ok-to-test, size/XXL

#334 add protocolDetectionTimeout
  global.yaml
Labels: cherrypick/release-1.3, cla: yes, size/S

#335 Fix Citadel clusterrole and tracing image
  istio-telemetry/tracing/values.yaml
  kustomize/citadel/citadel.yaml
  kustomize/default/gen-istio-autoinject.yaml
  kustomize/default/gen-istio-citadel.yaml
  kustomize/default/gen-istio-config.yaml
  kustomize/default/gen-istio-discovery.yaml
  kustomize/default/gen-istio-grafana.yaml
  kustomize/default/gen-istio-ingress.yaml
  kustomize/default/gen-istio-prometheus.yaml
  kustomize/default/gen-istio-telemetry.yaml
  kustomize/istio-canary/gen-discovery.yaml
  kustomize/minimal/gen-discovery.yaml
  security/citadel/templates/clusterrole.yaml
  test/demo/gen-citadel.yaml
  test/demo/gen-grafana.yaml
  test/demo/gen-tracing.yaml
Labels: cla: yes, size/XXL

#344 Fix test failures
  crds/files/crd-14.yaml
  crds/kustomization.yaml
  crds/templates/crds.yaml
  istio-control/istio-config/templates/clusterrole.yaml
  istio-control/istio-config/templates/validatingwebhookconfiguration.yaml.tpl
  istio-control/istio-discovery/templates/clusterrole.yaml
  istio-telemetry/kiali/templates/clusterrole.yaml
  kustomize/cluster/gen-crds-namespace.yaml
  kustomize/default/gen-istio-autoinject.yaml
  kustomize/default/gen-istio-config.yaml
  kustomize/default/gen-istio-discovery.yaml
  kustomize/minimal/gen-discovery.yaml
  test/demo/gen-galley.yaml
  test/demo/gen-inject-allns.yaml
  test/demo/gen-kiali.yaml
  test/demo/gen-pilot.yaml
Labels: cla: yes, size/L

#345 Use release-1.3 tag for release-1.3 branch
  .circleci/config.yml
  Makefile
  global.yaml
  istio-cni/values.yaml
  kustomize/citadel/citadel.yaml
  kustomize/default/gen-istio-autoinject.yaml
  kustomize/default/gen-istio-citadel.yaml
  kustomize/default/gen-istio-config.yaml
  kustomize/default/gen-istio-discovery.yaml
  kustomize/default/gen-istio-ingress.yaml
  kustomize/default/gen-istio-telemetry.yaml
  kustomize/istio-canary/gen-discovery.yaml
  kustomize/istio-ingress/gen-istio-ingress.yaml
  kustomize/minimal/gen-discovery.yaml
  test/canary/values.yaml
  test/demo/gen-egress.yaml
  test/demo/gen-grafana.yaml
  test/demo/gen-istio.yaml
  test/demo/gen-kiali.yaml
  test/demo/gen-policy.yaml
  test/demo/gen-prometheus.yaml
  test/demo/gen-tracing.yaml
  test/knative/gen-istio-ingress.yaml
  test/knative/values.yaml
  test/simple/values.yaml
Labels: cla: yes, size/XXL

#338 [release-1.3] Make HPA name consistent for ingressgateway
  gateways/istio-ingress/templates/autoscale.yaml
Labels: cla: yes, size/XS

#339 [release-1.3] fix error scale target reference in gateways hpa.
  gateways/istio-egress/templates/autoscale.yaml
  gateways/istio-ingress/templates/autoscale.yaml
Labels: cla: yes, size/XS

#342 cherry-pick mesh ID PR
  global.yaml
  istio-control/istio-autoinject/files/injection-template.yaml
Labels: cherrypick/release-1.3, cla: yes, size/M

#347 [release-1.3] cherry-pick mesh ID PR
  global.yaml
  istio-control/istio-autoinject/files/injection-template.yaml
Labels: cla: yes, size/M

#341 This repo is now handled by Tide.
  .mergify.yml
  README.md
Labels: cla: yes, size/S

#340 fix indention issue in egressgw env.
  gateways/istio-egress/values.yaml
Labels: cla: yes, size/S

#332 update rbac api version to v1.
  gateways/istio-ingress/templates/role.yaml
  istio-telemetry/prometheus-operator/templates/prometheus.yaml
  kustomize/citadel/citadel.yaml
  kustomize/default/gen-istio-citadel.yaml
  kustomize/istio-1.2/default/istio.yaml
  security/citadel/templates/clusterrole.yaml
  security/citadel/templates/clusterrolebinding.yaml
  test/demo/gen-citadel.yaml
  test/istio-system-1.0.6.yaml
Labels: cla: yes, size/M

#331 Update istionightly image
  .circleci/config.yml
  Makefile
  bin/ci2gubernator.sh
  test/docker/Dockerfile
Labels: cla: yes, size/M

#349 [release-1.3] fix indention issue in egressgw env.
  gateways/istio-egress/values.yaml
Labels: cla: yes, size/S

#323 Telemetry is broken when controlPlaneSecurity is disabled
  istio-policy/templates/deployment.yaml
  istio-telemetry/mixer-telemetry/templates/deployment.yaml
Labels: cla: yes, size/S

#362 Typo in istio-cni daemonset template
  istio-cni/templates/daemonset.yaml
Labels: cla: yes, needs-ok-to-test, size/XS

#363 Add license to shell file
  istio-telemetry/grafana/fix_datasources.sh
Labels: cherrypick/release-1.3, cla: yes, size/S

#365 [release-1.3] Add license to shell file
  istio-telemetry/grafana/fix_datasources.sh
Labels: cla: yes, size/S

#356 injector: includeInboundPorts set default to star #355
  istio-control/istio-autoinject/files/injection-template.yaml
  kustomize/citadel/citadel.yaml
  kustomize/default/gen-istio-autoinject.yaml
  kustomize/default/gen-istio-citadel.yaml
  kustomize/default/gen-istio-config.yaml
  kustomize/default/gen-istio-discovery.yaml
  kustomize/default/gen-istio-grafana.yaml
  kustomize/default/gen-istio-ingress.yaml
  kustomize/default/gen-istio-prometheus.yaml
  kustomize/default/gen-istio-telemetry.yaml
  kustomize/istio-canary/gen-discovery.yaml
  kustomize/minimal/gen-discovery.yaml
  test/demo/gen-egress.yaml
  test/demo/gen-grafana.yaml
  test/demo/gen-istio.yaml
  test/demo/gen-kiali.yaml
  test/demo/gen-prometheus.yaml
  test/demo/gen-tracing.yaml
Labels: cla: yes, size/M

#361 Update CoreDNS version to a more recent one
  istiocoredns/templates/configmap.yaml
  istiocoredns/templates/deployment.yaml
  istiocoredns/values.yaml
Labels: cla: yes, size/S

#364 Generate static configs based on 1.3rc
  Makefile
  kustomize/istio-1.3/default/gen-istio.yaml
  kustomize/istio-1.3/default/kustomization.yaml
  kustomize/istio-1.3/default/namespace.yaml
  kustomize/istio-1.3/default/values.yaml
  kustomize/istio-1.3/minimal/gen-istio.yaml
  kustomize/istio-1.3/minimal/kustomization.yaml
  kustomize/istio-1.3/minimal/namespace.yaml
  kustomize/istio-1.3/minimal/values-istio-minimal.yaml
  test/install.mk
Labels: cla: yes, size/XXL

#368 Grant Citadel namespace read permission to triage failing TestNamespaceTargeting test
  kustomize/citadel/citadel.yaml
  kustomize/cluster/clusterrole-12.yaml
  kustomize/default/gen-istio-citadel.yaml
  kustomize/istio-1.2/default/istio.yaml
  security/citadel/templates/clusterrole.yaml
  test/demo/gen-istio.yaml
Labels: cla: yes, size/S

#358 Use configNamespace for pilot instead of istioNamespace
  README.md
  gateways/istio-egress/templates/deployment.yaml
  gateways/istio-ingress/templates/deployment.yaml
  istio-control/istio-autoinject/templates/configmap.yaml
Labels: cla: yes, size/M

#353 Add context graph and mesh uid into stackdriver template
  istio-telemetry/mixer-telemetry/templates/stackdriver.yaml
  istio-telemetry/mixer-telemetry/values.yaml
Labels: cla: yes, size/M

#367 allow long protocol detection timeout for test
  global.yaml
Labels: cla: yes, size/XS
