Repository istio/installer, pull requests merged in 2019-10, with the labels that each got.

#343 feat(proxy templates): reflect istio/istio templates additions
  gateways/istio-egress/templates/deployment.yaml
  gateways/istio-ingress/templates/deployment.yaml
  istio-control/istio-autoinject/files/injection-template.yaml
Labels: cherrypick/release-1.3, cla: yes, size/S

#396 Add the possibility to create RoleBinding for PSP
  istio-cni/templates/clusterrolebinding.yaml
  istio-cni/values.yaml
Labels: cla: yes, size/S

#407 update hub and tag examples in readme
  README.md
Labels: cla: yes, size/S

#411 add objectSelector in istio-sidecar-injector MutatingWebhookConfigura…
  istio-control/istio-autoinject/templates/mutatingwebhook.yaml
  istio-control/istio-autoinject/values.yaml
Labels: cla: yes, size/S

#415 Setup stuff for prow jobs
  .circleci/config.yml
  Makefile.core.mk
  bin/with-kind.sh
  test/demo.mk
  test/kind/kind-prow.yaml
  test/noauth.mk
  test/tests.mk
Labels: cla: yes, size/L

#416 Update jaeger version to 1.14
  istio-telemetry/tracing/templates/deployment-jaeger.yaml
  istio-telemetry/tracing/templates/service-jaeger.yaml
  istio-telemetry/tracing/values.yaml
Labels: cla: yes, size/S

#418 Run `make build` and fix broken template
  gateways/istio-egress/templates/deployment.yaml
  kustomize/citadel/citadel.yaml
  kustomize/cluster/gen-crds-namespace.yaml
  kustomize/default/gen-istio-autoinject.yaml
  kustomize/default/gen-istio-citadel.yaml
  kustomize/default/gen-istio-config.yaml
  kustomize/default/gen-istio-discovery.yaml
  kustomize/default/gen-istio-grafana.yaml
  kustomize/default/gen-istio-ingress.yaml
  kustomize/default/gen-istio-prometheus.yaml
  kustomize/default/gen-istio-telemetry.yaml
  kustomize/istio-canary/gen-discovery.yaml
  kustomize/minimal/gen-discovery.yaml
  test/demo/gen-citadel.yaml
  test/demo/gen-egress.yaml
  test/demo/gen-galley.yaml
  test/demo/gen-grafana.yaml
  test/demo/gen-ingress.yaml
  test/demo/gen-inject-allns.yaml
  test/demo/gen-kiali.yaml
  test/demo/gen-pilot.yaml
  test/demo/gen-policy.yaml
  test/demo/gen-prometheus.yaml
  test/demo/gen-telemetry.yaml
  test/demo/gen-tracing.yaml
Labels: cla: yes, size/XL

#419 Remove circleci
  .circleci/config.yml
  README.md
Labels: cla: yes, size/L

#420 Add enableAnalysis for galley
  istio-control/istio-config/templates/deployment.yaml
  istio-control/istio-config/values.yaml
Labels: cla: yes, size/XS

#422 Support Citadel deployment to add random env variables
  security/citadel/templates/deployment.yaml
  security/citadel/values.yaml
Labels: cla: yes, size/S

#423 fix values path.
  security/citadel/templates/deployment.yaml
Labels: cla: yes, size/XS

#421 Support DNS certificate provision and management
  istio-control/istio-discovery/templates/clusterrole.yaml
  istio-control/istio-discovery/templates/configmap.yaml
  istio-control/istio-discovery/values.yaml
Labels: cla: yes, size/S

#427 Update common files.
  Makefile
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/license-lint.yml
  common/scripts/check_clean_repo.sh
Labels: cla: yes, size/M

#424 Enable DNS certificate provisioning
  global.yaml
  istio-control/istio-discovery/templates/clusterrole.yaml
  istio-control/istio-discovery/templates/configmap.yaml
  istio-control/istio-discovery/values.yaml
Labels: cla: yes, size/S

#429 Update common files.
  Makefile
  Makefile.core.mk
  common/.commonfiles.sha
  test/demo.mk
  test/noauth.mk
  test/tests.mk
Labels: cla: yes, size/M

#430 Use dev build instead of daily builds
  Makefile.core.mk
  README.md
  global.yaml
  kustomize/citadel/citadel.yaml
  kustomize/cluster/gen-crds-namespace.yaml
  kustomize/default/gen-istio-autoinject.yaml
  kustomize/default/gen-istio-citadel.yaml
  kustomize/default/gen-istio-config.yaml
  kustomize/default/gen-istio-discovery.yaml
  kustomize/default/gen-istio-grafana.yaml
  kustomize/default/gen-istio-ingress.yaml
  kustomize/default/gen-istio-prometheus.yaml
  kustomize/default/gen-istio-telemetry.yaml
  kustomize/istio-canary/gen-discovery.yaml
  kustomize/minimal/gen-discovery.yaml
  test/demo/gen-citadel.yaml
  test/demo/gen-egress.yaml
  test/demo/gen-galley.yaml
  test/demo/gen-grafana.yaml
  test/demo/gen-ingress.yaml
  test/demo/gen-inject-allns.yaml
  test/demo/gen-kiali.yaml
  test/demo/gen-pilot.yaml
  test/demo/gen-policy.yaml
  test/demo/gen-prometheus.yaml
  test/demo/gen-telemetry.yaml
  test/demo/gen-tracing.yaml
Labels: cla: yes, size/L

#428 Configure webhooks of Galley and Sidecar Injector based on DNS certificate provisioning
  global.yaml
  istio-control/istio-autoinject/templates/deployment.yaml
  istio-control/istio-config/templates/deployment.yaml
Labels: cla: yes, size/S

#417 [release-1.3] feat(proxy templates): reflect istio/istio templates additions
  gateways/istio-egress/templates/deployment.yaml
  gateways/istio-ingress/templates/deployment.yaml
  istio-control/istio-autoinject/files/injection-template.yaml
Labels: cla: yes, size/S

#431 Webhooks use DNS certificates provisioned by Chiron
  global.yaml
  istio-control/istio-autoinject/templates/deployment.yaml
  istio-control/istio-config/templates/deployment.yaml
  istio-control/istio-discovery/templates/configmap.yaml
  kustomize/default/gen-istio-discovery.yaml
  kustomize/istio-canary/gen-discovery.yaml
  kustomize/minimal/gen-discovery.yaml
  test/tests.mk
Labels: cla: yes, size/L

#425 use global.network to set ISTIO_META_NETWORK for sidecars and ingressgateway
  gateways/istio-ingress/templates/deployment.yaml
  global.yaml
Labels: cla: yes, size/XS

#433 Backport changes
  crds/files/crd-12.yaml
  crds/kustomization.yaml
  crds/templates/crds.yaml
  gateways/istio-egress/templates/deployment.yaml
  gateways/istio-egress/values.yaml
  gateways/istio-ingress/templates/deployment.yaml
  gateways/istio-ingress/templates/preconfigured.yaml
  global.yaml
  istio-control/istio-autoinject/files/injection-template.yaml
  istio-control/istio-autoinject/templates/deployment.yaml
  istio-control/istio-autoinject/templates/sidecar-injector-configmap.yaml
  istio-control/istio-autoinject/values.yaml
  istio-control/istio-config/templates/deployment.yaml
  istio-control/istio-discovery/templates/configmap.yaml
  istio-control/istio-discovery/templates/deployment.yaml
  istio-control/istio-discovery/values.yaml
  istio-policy/templates/deployment.yaml
  istio-policy/values.yaml
  istio-telemetry/grafana/dashboards/galley-dashboard.json
  istio-telemetry/grafana/templates/deployment.yaml
  istio-telemetry/grafana/values.yaml
  istio-telemetry/kiali/values.yaml
  istio-telemetry/mixer-telemetry/templates/config.yaml
  istio-telemetry/mixer-telemetry/templates/deployment.yaml
  istio-telemetry/mixer-telemetry/values.yaml
  istio-telemetry/prometheus-operator/values.yaml
  istio-telemetry/prometheus/values.yaml
  security/certmanager/values.yaml
  test/canary/values.yaml
  test/simple/values.yaml
Labels: cla: yes, size/L

#436 Move changes to structural CRDs to installer
  crds/files/crd-10.yaml
  crds/files/crd-11.yaml
  crds/files/crd-14.yaml
Labels: cla: yes, size/XXL

#437 Update for release-1.4
  CODEOWNERS
  Makefile
  README.md
  common/.commonfiles.sha
  common/Makefile.common.mk
  global.yaml
  istio-cni/values.yaml
  test/canary/values.yaml
  test/knative/values.yaml
  test/simple/values.yaml
Labels: cla: yes, size/M

#438 Fix values for knative
  test/knative/values.yaml
Labels: cla: yes, size/XS

#439 No deploy of mutatingwebhookconfiguration when operatorManageWebhooks is true
  istio-control/istio-autoinject/templates/mutatingwebhook.yaml
Labels: cla: yes, size/XS

#441 When Operator manages webhooks, Galley and Sidecar Injector are deprivileged
  istio-control/istio-autoinject/templates/clusterrole.yaml
  istio-control/istio-config/templates/clusterrole.yaml
Labels: cla: yes, size/XS

#434 Remove old Istio charts
  kustomize/istio-1.2/default/istio.yaml
  kustomize/istio-1.2/default/kustomization.yaml
  kustomize/istio-1.2/default/namespace.yaml
  kustomize/istio-1.2/default/values.yaml
  kustomize/istio-1.2/minimal/istio.yaml
  kustomize/istio-1.2/minimal/kustomization.yaml
  kustomize/istio-1.2/minimal/namespace.yaml
  kustomize/istio-1.2/minimal/values-istio-minimal.yaml
  kustomize/istio-1.3/default/gen-istio.yaml
  kustomize/istio-1.3/default/kustomization.yaml
  kustomize/istio-1.3/default/namespace.yaml
  kustomize/istio-1.3/default/values.yaml
  kustomize/istio-1.3/minimal/gen-istio.yaml
  kustomize/istio-1.3/minimal/kustomization.yaml
  kustomize/istio-1.3/minimal/namespace.yaml
  kustomize/istio-1.3/minimal/values-istio-minimal.yaml
  test/canary/canary.mk
  test/install.mk
Labels: cla: yes, size/XXL

#440 Add trust domain and trust domain aliases to Pilot configmap
  global.yaml
  istio-control/istio-discovery/templates/configmap.yaml
Labels: cherrypick/release-1.4, cla: yes, size/S

#432 Add LDAP support to Kiali
  istio-telemetry/kiali/Chart.yaml
  istio-telemetry/kiali/templates/configmap.yaml
  istio-telemetry/kiali/templates/demosecret.yaml
  istio-telemetry/kiali/values.yaml
Labels: cla: yes, ok-to-test, size/M

#443 Istiod templates
  kustomize/cluster/istiod.yaml
  kustomize/cluster/kustomization.yaml
  kustomize/istiod/istiod.yaml
  kustomize/istiod/kustomization.yaml
Labels: cla: yes, size/L

#442 [release-1.4] Add trust domain and trust domain aliases to Pilot configmap
  global.yaml
  istio-control/istio-discovery/templates/configmap.yaml
Labels: cla: yes, size/S

#444 change egress hpa name to consume operator requirement
  gateways/istio-egress/templates/autoscale.yaml
Labels: cla: yes, size/XS

#445 change egress hpa name to consume operator requirement (#444)
  gateways/istio-egress/templates/autoscale.yaml
Labels: cla: yes, size/XS

#446 Auto mtls on by default.
  global.yaml
Labels: cla: yes, size/XS

#448 auto mtls on by default in demo, used in istio/istio test
  test/demo/values.yaml
Labels: cherrypick/release-1.4, cla: yes, size/XS

#449 [release-1.4] auto mtls on by default in demo, used in istio/istio test
  test/demo/values.yaml
Labels: cla: yes, size/XS

#451 Update installer to use 1.4-dev
  Makefile.core.mk
  kustomize/citadel/citadel.yaml
  kustomize/default/gen-istio-autoinject.yaml
  kustomize/default/gen-istio-citadel.yaml
  kustomize/default/gen-istio-config.yaml
  kustomize/default/gen-istio-discovery.yaml
  kustomize/default/gen-istio-ingress.yaml
  kustomize/default/gen-istio-telemetry.yaml
  kustomize/istio-canary/gen-discovery.yaml
  kustomize/istio-ingress/gen-istio-ingress.yaml
  kustomize/minimal/gen-discovery.yaml
  test/demo/gen-citadel.yaml
  test/demo/gen-egress.yaml
  test/demo/gen-galley.yaml
  test/demo/gen-ingress.yaml
  test/demo/gen-inject-allns.yaml
  test/demo/gen-pilot.yaml
  test/demo/gen-policy.yaml
  test/demo/gen-telemetry.yaml
  test/knative/gen-istio-ingress.yaml
Labels: cla: yes, size/M

#452 Manually CP ${root}/global.yaml change for autoMTLS
  global.yaml
Labels: cla: yes, size/XS

#453 Charts for: Custom root certificates for JWKSResolver (istio/istio#17176)
  istio-control/istio-discovery/templates/configmap-jwks.yaml
  istio-control/istio-discovery/templates/deployment.yaml
  istio-control/istio-discovery/values.yaml
Labels: cla: yes, ok-to-test, size/S

#450 create MeshPolicy using global.mtls.enabled
  istio-control/istio-discovery/templates/enable-mesh-mtls.yaml
Labels: cla: yes, size/M

#455 Revert auto mtls
  global.yaml
  test/demo/values.yaml
Labels: cla: yes, size/XS

#456 create MeshPolicy using global.mtls.enabled
  istio-control/istio-discovery/templates/enable-mesh-mtls.yaml
Labels: cla: yes, size/M

#435 Rename generated files to .gen.yaml
  kustomize/cluster/crds-namespace.gen.yaml
  kustomize/cluster/kustomization.yaml
  kustomize/default/istio-autoinject.gen.yaml
  kustomize/default/istio-citadel.gen.yaml
  kustomize/default/istio-config.gen.yaml
  kustomize/default/istio-discovery.gen.yaml
  kustomize/default/istio-grafana.gen.yaml
  kustomize/default/istio-ingress.gen.yaml
  kustomize/default/istio-prometheus.gen.yaml
  kustomize/default/istio-telemetry.gen.yaml
  kustomize/default/kustomization.yaml
  kustomize/istio-canary/discovery.gen.yaml
  kustomize/istio-canary/kustomization.yaml
  kustomize/istio-ingress/istio-ingress.gen.yaml
  kustomize/istio-ingress/kustomization.yaml
  kustomize/minimal/discovery.gen.yaml
  kustomize/minimal/kustomization.yaml
  test/demo/citadel.gen.yaml
  test/demo/egress.gen.yaml
  test/demo/galley.gen.yaml
  test/demo/grafana.gen.yaml
  test/demo/ingress.gen.yaml
  test/demo/inject-allns.gen.yaml
  test/demo/kiali.gen.yaml
  test/demo/kustomization.yaml
  test/demo/pilot.gen.yaml
  test/demo/policy.gen.yaml
  test/demo/prometheus.gen.yaml
  test/demo/telemetry.gen.yaml
  test/demo/tracing.gen.yaml
  test/install.mk
  test/knative/istio-ingress.gen.yaml
  test/knative/kustomization.yaml
Labels: cla: yes, size/M

#458 Fix kind cleanup to prevent leak
  bin/with-kind.sh
Labels: cla: yes, size/XS

#460 [release-1.4] Fix kind cleanup to prevent leak
  bin/with-kind.sh
Labels: cla: yes, size/XS

#461 Update common files.
  Makefile
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/.golangci.yml
  common/scripts/check_clean_repo.sh
  common/scripts/lint_go.sh
  common/scripts/report_build_info.sh
Labels: cla: yes, size/M

#459 Revert "auto mtls on by default (#446) (#452)"
  global.yaml
  test/demo/values.yaml
Labels: cla: yes, size/XS

#463 remove namespace for meshpolicy resource.
  istio-control/istio-discovery/templates/enable-mesh-mtls.yaml
Labels: cherrypick/release-1.4, cla: yes, size/XS

#464 [release-1.4] remove namespace for meshpolicy resource.
  istio-control/istio-discovery/templates/enable-mesh-mtls.yaml
Labels: cla: yes, size/XS

#465 remove the usage of applicationPorts
  bin/env.sh
  gateways/istio-ingress/templates/deployment.yaml
  gateways/istio-ingress/values.yaml
  istio-control/istio-autoinject/files/injection-template.yaml
  kustomize/default/istio-autoinject.gen.yaml
  test/demo/inject-allns.gen.yaml
Labels: cla: yes, size/S

#466 Update common files.
  Makefile
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/check_clean_repo.sh
  common/scripts/report_build_info.sh
Labels: cla: yes, size/M

#457 Generate files and add gencheck target
  Makefile.core.mk
  kustomize/citadel/citadel.yaml
  kustomize/cluster/crds-namespace.gen.yaml
  kustomize/default/istio-autoinject.gen.yaml
  kustomize/default/istio-citadel.gen.yaml
  kustomize/default/istio-config.gen.yaml
  kustomize/default/istio-discovery.gen.yaml
  kustomize/default/istio-grafana.gen.yaml
  kustomize/default/istio-ingress.gen.yaml
  kustomize/default/istio-prometheus.gen.yaml
  kustomize/default/istio-telemetry.gen.yaml
  kustomize/istio-canary/discovery.gen.yaml
  kustomize/minimal/discovery.gen.yaml
  test/demo/egress.gen.yaml
  test/demo/galley.gen.yaml
  test/demo/grafana.gen.yaml
  test/demo/ingress.gen.yaml
  test/demo/inject-allns.gen.yaml
  test/demo/kiali.gen.yaml
  test/demo/pilot.gen.yaml
  test/demo/policy.gen.yaml
  test/demo/prometheus.gen.yaml
  test/demo/telemetry.gen.yaml
Labels: cla: yes, size/M

#468 Run gen
  kustomize/default/istio-discovery.gen.yaml
  kustomize/minimal/discovery.gen.yaml
  test/demo/pilot.gen.yaml
Labels: cla: yes, size/XS

#469 make run-build after setting global.mtls.auto true in globa.yaml
  global.yaml
  kustomize/default/istio-autoinject.gen.yaml
  kustomize/default/istio-discovery.gen.yaml
  kustomize/istio-canary/discovery.gen.yaml
  kustomize/minimal/discovery.gen.yaml
  test/demo/inject-allns.gen.yaml
  test/demo/pilot.gen.yaml
Labels: cherrypick/release-1.4, cla: yes, size/XS

#470 Manual CP for auto mtls for 1.4
  global.yaml
  kustomize/default/gen-istio-autoinject.yaml
  kustomize/default/gen-istio-discovery.yaml
  kustomize/istio-canary/gen-discovery.yaml
  kustomize/minimal/gen-discovery.yaml
  test/demo/gen-inject-allns.yaml
  test/demo/gen-pilot.yaml
Labels: cla: yes, size/S

#471 Turn off DNS certificate provisioning
  global.yaml
  kustomize/default/istio-autoinject.gen.yaml
  kustomize/default/istio-config.gen.yaml
  kustomize/default/istio-discovery.gen.yaml
  kustomize/istio-canary/discovery.gen.yaml
  kustomize/minimal/discovery.gen.yaml
  test/demo/galley.gen.yaml
  test/demo/inject-allns.gen.yaml
  test/demo/pilot.gen.yaml
Labels: cla: yes, size/XS

#475 Revert auto mtls on by default in 1.4
  global.yaml
  kustomize/default/gen-istio-autoinject.yaml
  kustomize/default/gen-istio-discovery.yaml
  kustomize/istio-canary/gen-discovery.yaml
  kustomize/minimal/gen-discovery.yaml
  test/demo/gen-inject-allns.yaml
  test/demo/gen-pilot.yaml
Labels: cla: yes, size/S
