Repository istio/installer, pull requests merged in 2019-11, with the labels that each got.

#467 Add mixerv2 telemetry install option
  istio-control/istio-discovery/metadata-exchange-v2.yaml
  istio-control/istio-discovery/stats-filter-v2.yaml
  istio-control/istio-discovery/templates/configmap.yaml
  istio-control/istio-discovery/templates/telemetryv2.yaml
  istio-control/istio-discovery/values.yaml
  kustomize/default/istio-discovery.gen.yaml
  kustomize/istio-canary/discovery.gen.yaml
  kustomize/minimal/discovery.gen.yaml
  test/demo/pilot.gen.yaml
Labels: cla: yes, size/L

#479 Match CRD files in istio/istio
  crds/files/crd-11.yaml
  crds/files/crd-14.yaml
  crds/files/crd-all.gen.yaml
  crds/files/crd-mixer.yaml
  crds/kustomization.yaml
  crds/templates/crds.yaml
  kustomize/cluster/crds-namespace.gen.yaml
Labels: cla: yes, size/L

#478 remove duplicate field
  istio-telemetry/mixer-telemetry/templates/config.yaml
  kustomize/default/istio-telemetry.gen.yaml
  test/demo/telemetry.gen.yaml
Labels: cla: yes, size/XS

#477 Sync CNI charts from istio/cni
  istio-cni/Chart.yaml
  istio-cni/templates/daemonset.yaml
  istio-cni/values.yaml
  istio-cni/values_gke.yaml
Labels: cherrypick/release-1.4, cla: yes, size/M

#481 Sync CNI charts from istio/cni
  istio-cni/Chart.yaml
  istio-cni/templates/daemonset.yaml
  istio-cni/values.yaml
  istio-cni/values_gke.yaml
Labels: cla: yes, size/M

#480 Remove rendered istio 1.0.6 yaml
  test/istio-system-1.0.6.yaml
Labels: cla: yes, size/XXL

#482 CNI: Use global hub & tag by default
  istio-cni/templates/daemonset.yaml
  istio-cni/values.yaml
Labels: cherrypick/release-1.4, cla: yes, size/S

#484 [release-1.4] CNI: Use global hub & tag by default (#482)
  istio-cni/templates/daemonset.yaml
  istio-cni/values.yaml
Labels: cla: yes, size/S

#483 Fix mtls Destinationrules
  istio-telemetry/prometheus-operator/templates/prometheus.yaml
  istio-telemetry/prometheus/templates/destination-rule.yaml
  kustomize/default/istio-prometheus.gen.yaml
  test/demo/prometheus.gen.yaml
Labels: cla: yes, size/S

#487 [release-1.4] Fix mtls Destinationrules
  istio-telemetry/prometheus-operator/templates/prometheus.yaml
  istio-telemetry/prometheus/templates/destination-rule.yaml
  kustomize/default/gen-istio-prometheus.yaml
  test/demo/gen-prometheus.yaml
Labels: cla: yes, size/M

#488 add permissions to be able to view logs in kiali console
  istio-telemetry/kiali/templates/clusterrole.yaml
  test/demo/kiali.gen.yaml
Labels: cherrypick/release-1.4, cla: yes, size/XS

#491 [release-1.4] add permissions to be able to view logs in kiali console
  istio-telemetry/kiali/templates/clusterrole.yaml
  test/demo/gen-kiali.yaml
Labels: cla: yes, size/XS

#493 Use global trust domain
  istio-control/istio-discovery/templates/configmap.yaml
  kustomize/citadel/citadel.yaml
  kustomize/default/istio-citadel.gen.yaml
  kustomize/default/istio-discovery.gen.yaml
  kustomize/istio-canary/discovery.gen.yaml
  kustomize/minimal/discovery.gen.yaml
  security/citadel/templates/deployment.yaml
  security/citadel/values.yaml
  test/demo/citadel.gen.yaml
  test/demo/pilot.gen.yaml
Labels: cherrypick/release-1.4, cla: yes, size/XS

#494 [release-1.4] Use global trust domain
  istio-control/istio-discovery/templates/configmap.yaml
  kustomize/citadel/citadel.yaml
  kustomize/default/gen-istio-citadel.yaml
  kustomize/default/gen-istio-discovery.yaml
  kustomize/istio-canary/gen-discovery.yaml
  kustomize/minimal/gen-discovery.yaml
  security/citadel/templates/deployment.yaml
  security/citadel/values.yaml
  test/demo/gen-citadel.yaml
  test/demo/gen-pilot.yaml
Labels: cla: yes, size/S

#492 add istio-reader clusterrole to access remote clusters with reduced privileges
  istio-control/istio-discovery/templates/clusterrole.yaml
  kustomize/default/istio-discovery.gen.yaml
  kustomize/minimal/discovery.gen.yaml
  test/demo/pilot.gen.yaml
Labels: cherrypick/release-1.4, cla: yes, size/S

#495 [release-1.4] add istio-reader clusterrole to access remote clusters with reduced privileges
  istio-control/istio-discovery/templates/clusterrole.yaml
  kustomize/default/gen-istio-discovery.yaml
  kustomize/minimal/gen-discovery.yaml
  test/demo/gen-pilot.yaml
Labels: cla: yes, size/M

#496 Move up grafana to latest
  istio-telemetry/grafana/values.yaml
  kustomize/default/istio-grafana.gen.yaml
  test/demo/grafana.gen.yaml
Labels: cla: yes, size/XS

#489 Kill unneeded/broken DestinationRules
  istio-control/istio-discovery/templates/enable-mesh-mtls.yaml
  istio-telemetry/grafana/templates/destination-rule.yaml
  istio-telemetry/prometheus-operator/templates/prometheus.yaml
  istio-telemetry/prometheus/templates/destination-rule.yaml
  kustomize/default/istio-discovery.gen.yaml
  kustomize/default/istio-grafana.gen.yaml
  kustomize/default/istio-prometheus.gen.yaml
  kustomize/minimal/discovery.gen.yaml
  test/demo/grafana.gen.yaml
  test/demo/pilot.gen.yaml
  test/demo/prometheus.gen.yaml
Labels: cherrypick/release-1.4, cla: yes, size/M

#499 [release-1.4] Kill unneeded/broken DestinationRules
  istio-control/istio-discovery/templates/enable-mesh-mtls.yaml
  istio-telemetry/grafana/templates/destination-rule.yaml
  istio-telemetry/prometheus-operator/templates/prometheus.yaml
  istio-telemetry/prometheus/templates/destination-rule.yaml
  kustomize/default/gen-istio-discovery.yaml
  kustomize/default/gen-istio-grafana.yaml
  kustomize/default/gen-istio-prometheus.yaml
  kustomize/minimal/gen-discovery.yaml
  test/demo/gen-grafana.yaml
  test/demo/gen-pilot.yaml
  test/demo/gen-prometheus.yaml
Labels: cla: yes, size/L

#502 No ISTIO_MUTUAL DestinationRule if auto mTLS is enabled.
  istio-control/istio-discovery/templates/enable-mesh-mtls.yaml
  kustomize/default/istio-discovery.gen.yaml
  kustomize/minimal/discovery.gen.yaml
  test/demo/pilot.gen.yaml
Labels: cla: yes, size/XS

#501 update grafana versions
  istio-telemetry/grafana/values.yaml
  kustomize/default/gen-istio-grafana.yaml
  test/demo/gen-grafana.yaml
Labels: cla: yes, size/XS

#503 [kiali] update to Kiali v1.9
  istio-telemetry/kiali/Chart.yaml
  istio-telemetry/kiali/templates/clusterrole.yaml
  istio-telemetry/kiali/templates/configmap.yaml
  istio-telemetry/kiali/templates/deployment.yaml
  istio-telemetry/kiali/values.yaml
  test/demo/kiali.gen.yaml
Labels: cherrypick/release-1.4, cla: yes, size/S

#498 Remove usages of cluster.local directly
  gateways/istio-ingress/templates/meshexpansion.yaml
  istio-control/istio-discovery/templates/enable-mesh-mtls.yaml
Labels: cherrypick/release-1.4, cla: yes, size/S

#504 [kiali] update to kiali 1.9 (cherry pick of PR #503)
  istio-telemetry/kiali/Chart.yaml
  istio-telemetry/kiali/templates/clusterrole.yaml
  istio-telemetry/kiali/templates/configmap.yaml
  istio-telemetry/kiali/templates/deployment.yaml
  istio-telemetry/kiali/values.yaml
  test/demo/gen-kiali.yaml
Labels: cla: yes, size/M

#500 Align injection template to fix SDS
  global.yaml
  istio-control/istio-autoinject/files/injection-template.yaml
  istio-control/istio-autoinject/templates/configmap.yaml
  kustomize/citadel/citadel.yaml
  kustomize/default/istio-autoinject.gen.yaml
  kustomize/default/istio-citadel.gen.yaml
  kustomize/default/istio-config.gen.yaml
  kustomize/default/istio-discovery.gen.yaml
  kustomize/default/istio-grafana.gen.yaml
  kustomize/default/istio-ingress.gen.yaml
  kustomize/default/istio-prometheus.gen.yaml
  kustomize/default/istio-telemetry.gen.yaml
  kustomize/istio-canary/discovery.gen.yaml
  kustomize/minimal/discovery.gen.yaml
  test/demo/citadel.gen.yaml
  test/demo/egress.gen.yaml
  test/demo/galley.gen.yaml
  test/demo/grafana.gen.yaml
  test/demo/ingress.gen.yaml
  test/demo/inject-allns.gen.yaml
  test/demo/kiali.gen.yaml
  test/demo/pilot.gen.yaml
  test/demo/policy.gen.yaml
  test/demo/prometheus.gen.yaml
  test/demo/telemetry.gen.yaml
  test/demo/tracing.gen.yaml
Labels: cherrypick/release-1.4, cla: yes, size/S

#505 [release-1.4] Remove usages of cluster.local directly
  gateways/istio-ingress/templates/meshexpansion.yaml
  istio-control/istio-discovery/templates/enable-mesh-mtls.yaml
Labels: cla: yes, size/S

#497 Sync pilot readiness with istio/istio
  istio-control/istio-discovery/templates/deployment.yaml
  kustomize/default/istio-discovery.gen.yaml
  kustomize/istio-canary/discovery.gen.yaml
  kustomize/minimal/discovery.gen.yaml
  test/demo/pilot.gen.yaml
Labels: cherrypick/release-1.4, cla: yes, size/XS

#506 Fix Galley trust domain in config map and make cluster.local default
  global.yaml
  istio-control/istio-discovery/templates/configmap-envoy.yaml
  istio-telemetry/mixer-telemetry/templates/configmap-envoy.yaml
  kustomize/citadel/citadel.yaml
  kustomize/default/istio-autoinject.gen.yaml
  kustomize/default/istio-citadel.gen.yaml
  kustomize/default/istio-config.gen.yaml
  kustomize/default/istio-discovery.gen.yaml
  kustomize/default/istio-ingress.gen.yaml
  kustomize/default/istio-telemetry.gen.yaml
  kustomize/istio-canary/discovery.gen.yaml
  kustomize/minimal/discovery.gen.yaml
  test/demo/citadel.gen.yaml
  test/demo/egress.gen.yaml
  test/demo/galley.gen.yaml
  test/demo/ingress.gen.yaml
  test/demo/inject-allns.gen.yaml
  test/demo/pilot.gen.yaml
  test/demo/policy.gen.yaml
  test/demo/telemetry.gen.yaml
Labels: cherrypick/release-1.4, cla: yes, size/XS

#507 [release-1.4] Sync pilot readiness with istio/istio
  istio-control/istio-discovery/templates/deployment.yaml
  kustomize/default/gen-istio-discovery.yaml
  kustomize/istio-canary/gen-discovery.yaml
  kustomize/minimal/gen-discovery.yaml
  test/demo/gen-pilot.yaml
Labels: cla: yes, size/S

#509 Move auto mtls dr guard to correct block
  istio-control/istio-discovery/templates/enable-mesh-mtls.yaml
Labels: cla: yes, size/XS

#508 add missing istio-reader service account and binding
  istio-control/istio-discovery/templates/clusterrole.yaml
  istio-control/istio-discovery/templates/clusterrolebinding.yaml
  istio-control/istio-discovery/templates/serviceaccount.yaml
  kustomize/default/istio-discovery.gen.yaml
  kustomize/minimal/discovery.gen.yaml
  test/demo/pilot.gen.yaml
Labels: cherrypick/release-1.4, cla: yes, size/M

#510 [release-1.4] add missing istio-reader service account and binding
  istio-control/istio-discovery/templates/clusterrole.yaml
  istio-control/istio-discovery/templates/clusterrolebinding.yaml
  istio-control/istio-discovery/templates/serviceaccount.yaml
  kustomize/default/gen-istio-discovery.yaml
  kustomize/minimal/gen-discovery.yaml
  test/demo/gen-pilot.yaml
Labels: cla: yes, size/L

#512 [release-1.4] Fix Galley trust domain and make cluster.local default
  global.yaml
  istio-control/istio-discovery/templates/configmap-envoy.yaml
  istio-telemetry/mixer-telemetry/templates/configmap-envoy.yaml
  kustomize/citadel/citadel.yaml
  kustomize/default/gen-istio-citadel.yaml
  kustomize/default/gen-istio-config.yaml
  kustomize/default/gen-istio-discovery.yaml
  kustomize/default/gen-istio-ingress.yaml
  kustomize/default/gen-istio-telemetry.yaml
  kustomize/istio-canary/gen-discovery.yaml
  kustomize/minimal/gen-discovery.yaml
  test/demo/gen-citadel.yaml
  test/demo/gen-egress.yaml
  test/demo/gen-galley.yaml
  test/demo/gen-ingress.yaml
  test/demo/gen-pilot.yaml
  test/demo/gen-policy.yaml
  test/demo/gen-telemetry.yaml
Labels: cla: yes, size/M

#511 automtls=true global=true case in 1.4
  istio-control/istio-discovery/templates/enable-mesh-mtls.yaml
Labels: cla: yes, size/XS

#513 Align injection template to fix SDS (#500)
  global.yaml
  istio-control/istio-autoinject/files/injection-template.yaml
  istio-control/istio-autoinject/templates/configmap.yaml
  kustomize/citadel/citadel.yaml
  kustomize/default/gen-istio-autoinject.yaml
  kustomize/default/gen-istio-citadel.yaml
  kustomize/default/gen-istio-config.yaml
  kustomize/default/gen-istio-discovery.yaml
  kustomize/default/gen-istio-grafana.yaml
  kustomize/default/gen-istio-ingress.yaml
  kustomize/default/gen-istio-prometheus.yaml
  kustomize/default/gen-istio-telemetry.yaml
  kustomize/istio-canary/gen-discovery.yaml
  kustomize/minimal/gen-discovery.yaml
  test/demo/gen-citadel.yaml
  test/demo/gen-egress.yaml
  test/demo/gen-galley.yaml
  test/demo/gen-grafana.yaml
  test/demo/gen-ingress.yaml
  test/demo/gen-inject-allns.yaml
  test/demo/gen-kiali.yaml
  test/demo/gen-pilot.yaml
  test/demo/gen-policy.yaml
  test/demo/gen-prometheus.yaml
  test/demo/gen-telemetry.yaml
  test/demo/gen-tracing.yaml
Labels: cla: yes, size/M

#514 Update jaeger yaml to include the jaeger-agent svc
  istio-telemetry/tracing/templates/service-jaeger.yaml
  test/demo/tracing.gen.yaml
Labels: cherrypick/release-1.4, cla: yes, size/S

#515 [release-1.4] Update jaeger yaml to include the jaeger-agent svc
  istio-telemetry/tracing/templates/service-jaeger.yaml
  test/demo/gen-tracing.yaml
Labels: cla: yes, size/M

#490 Add missing remote resources
  .concourse/concourse.yaml
  .drone.yml
  README.md
  base/Chart.yaml
  base/files/crd-all.gen.yaml
  base/files/crd-certmanager-10.yaml
  base/files/crd-certmanager-11.yaml
  base/files/crd-mixer.yaml
  base/kustomization.yaml
  base/templates/clusterrole.yaml
  base/templates/crds.yaml
  base/templates/endpoints.yaml
  base/templates/namespaces.yaml
  base/templates/services.yaml
  base/values.yaml
  global.yaml
  istio-control/istio-discovery/templates/clusterrole.yaml
  istio-control/istio-discovery/templates/configmap.yaml
  istio-control/istio-discovery/values.yaml
  kustomize/cluster/crds-namespace.gen.yaml
  kustomize/default/istio-autoinject.gen.yaml
  kustomize/default/istio-discovery.gen.yaml
  kustomize/istio-canary/discovery.gen.yaml
  kustomize/minimal/discovery.gen.yaml
  test/demo/example/kustomization.yaml
  test/demo/inject-allns.gen.yaml
  test/demo/pilot.gen.yaml
  test/install.mk
  test/tests.mk
Labels: cherrypick/release-1.4, cla: yes, size/L

#516 Fix grafana datasources value
  istio-telemetry/grafana/templates/configmap.yaml
  istio-telemetry/grafana/values.yaml
  kustomize/default/istio-grafana.gen.yaml
  test/demo/grafana.gen.yaml
Labels: cherrypick/release-1.4, cla: yes, size/M

#518 [release-1.4] Fix grafana datasources value
  istio-telemetry/grafana/templates/configmap.yaml
  istio-telemetry/grafana/values.yaml
  kustomize/default/gen-istio-grafana.yaml
  test/demo/gen-grafana.yaml
Labels: cla: yes, size/M

#517 [release-1.4] Add missing remote resources (#490)
  .concourse/concourse.yaml
  .drone.yml
  README.md
  base/Chart.yaml
  base/files/crd-10.yaml
  base/files/crd-11.yaml
  base/files/crd-14.yaml
  base/files/crd-certmanager-10.yaml
  base/files/crd-certmanager-11.yaml
  base/kustomization.yaml
  base/templates/clusterrole.yaml
  base/templates/crds.yaml
  base/templates/endpoints.yaml
  base/templates/namespaces.yaml
  base/templates/services.yaml
  base/values.yaml
  global.yaml
  istio-control/istio-discovery/templates/clusterrole.yaml
  istio-control/istio-discovery/templates/configmap.yaml
  istio-control/istio-discovery/values.yaml
  kustomize/cluster/gen-crds-namespace.yaml
  kustomize/default/gen-istio-autoinject.yaml
  kustomize/default/gen-istio-discovery.yaml
  kustomize/istio-canary/gen-discovery.yaml
  kustomize/minimal/gen-discovery.yaml
  test/demo/example/kustomization.yaml
  test/demo/gen-inject-allns.yaml
  test/demo/gen-pilot.yaml
  test/demo/values.yaml
  test/install.mk
  test/tests.mk
Labels: cla: yes, size/XXL

#485 Update envoy metrics service and access log service config
  gateways/istio-ingress/templates/deployment.yaml
  global.yaml
  istio-control/istio-autoinject/files/injection-template.yaml
  istio-control/istio-discovery/templates/configmap.yaml
  kustomize/cluster/crds-namespace.gen.yaml
  kustomize/default/istio-autoinject.gen.yaml
  test/canary/mesh.yaml
  test/canary/values.yaml
  test/demo/inject-allns.gen.yaml
  test/demo/mesh.yaml
  test/knative/mesh.yaml
  test/knative/values.yaml
  test/simple/mesh.yaml
  test/simple/values.yaml
Labels: cla: yes, ok-to-test, size/M

#519 [kiali] issue-18798 fix some wrong yaml.
  istio-telemetry/kiali/templates/clusterrole.yaml
  istio-telemetry/kiali/templates/configmap.yaml
  kustomize/cluster/crds-namespace.gen.yaml
  test/demo/kiali.gen.yaml
Labels: cherrypick/release-1.4, cla: yes, size/S

#520 [release-1.4] [kiali] issue-18798 fix some wrong yaml.
  istio-telemetry/kiali/templates/clusterrole.yaml
  istio-telemetry/kiali/templates/configmap.yaml
  kustomize/cluster/gen-crds-namespace.yaml
  test/demo/gen-kiali.yaml
Labels: cla: yes, size/M

#521 Fix sds jwt
  gateways/istio-egress/templates/deployment.yaml
  gateways/istio-ingress/templates/deployment.yaml
  istio-control/istio-discovery/templates/deployment.yaml
  istio-policy/templates/deployment.yaml
  istio-telemetry/mixer-telemetry/templates/deployment.yaml
  kustomize/cluster/crds-namespace.gen.yaml
Labels: cherrypick/release-1.4, cla: yes, size/S

#522 [release-1.4] Fix sds jwt
  gateways/istio-egress/templates/deployment.yaml
  gateways/istio-ingress/templates/deployment.yaml
  istio-control/istio-discovery/templates/deployment.yaml
  istio-policy/templates/deployment.yaml
  istio-telemetry/mixer-telemetry/templates/deployment.yaml
  kustomize/cluster/gen-crds-namespace.yaml
Labels: cla: yes, size/M

#523 Support mixerv2
  istio-control/istio-discovery/metadata-exchange-v2.yaml
  istio-control/istio-discovery/stats-filter-v2.yaml
  istio-control/istio-discovery/templates/configmap.yaml
  istio-control/istio-discovery/templates/telemetryv2.yaml
  istio-control/istio-discovery/values.yaml
Labels: cla: yes, size/L

#526 [cherrypick] PR 441 and 439 from master branch to release 1.4 branch
  istio-control/istio-autoinject/templates/clusterrole.yaml
  istio-control/istio-autoinject/templates/mutatingwebhook.yaml
  istio-control/istio-config/templates/clusterrole.yaml
Labels: cla: yes, size/XS

#531 Modify prom operator root path
  istio-telemetry/prometheus-operator/templates/prometheus.yaml
  istio-telemetry/prometheus-operator/templates/servicemonitors.yaml
  istio-telemetry/prometheus-operator/values.yaml
  kustomize/cluster/crds-namespace.gen.yaml
Labels: cherrypick/release-1.4, cla: yes, size/M

#532 [release-1.4] Modify prom operator root path
  istio-telemetry/prometheus-operator/templates/prometheus.yaml
  istio-telemetry/prometheus-operator/templates/servicemonitors.yaml
  istio-telemetry/prometheus-operator/values.yaml
  kustomize/cluster/gen-crds-namespace.yaml
Labels: cla: yes, size/M

#535 Show diff from gencheck
  Makefile
  Makefile.core.mk
Labels: cla: yes, size/XS

#537 Updated mixer config to bring in latest changes
  istio-telemetry/mixer-telemetry/templates/config.yaml
  kustomize/default/istio-telemetry.gen.yaml
  test/demo/telemetry.gen.yaml
Labels: cherrypick/release-1.3, cherrypick/release-1.4, cla: yes, size/S

#538 [release-1.4] Updated mixer config to bring in latest changes
  istio-telemetry/mixer-telemetry/templates/config.yaml
  kustomize/default/gen-istio-telemetry.yaml
  test/demo/gen-telemetry.yaml
Labels: cla: yes, size/M

#529 Update galley-dashboard.json
  istio-telemetry/grafana/dashboards/galley-dashboard.json
  kustomize/default/istio-grafana.gen.yaml
  test/demo/grafana.gen.yaml
Labels: cherrypick/release-1.4, cla: yes, size/XS

#536 Add health check to Citadel.
  security/citadel/templates/deployment.yaml
  security/citadel/values.yaml
Labels: cla: yes, size/S

#539 [release-1.4] Update galley-dashboard.json
  istio-telemetry/grafana/dashboards/galley-dashboard.json
  kustomize/default/gen-istio-grafana.yaml
  test/demo/gen-grafana.yaml
Labels: cla: yes, size/S

#533 Sync labels with istio/istio
  gateways/istio-egress/templates/autoscale.yaml
  gateways/istio-egress/templates/service.yaml
  gateways/istio-ingress/templates/autoscale.yaml
  gateways/istio-ingress/templates/service.yaml
  istio-control/istio-autoinject/templates/deployment.yaml
  istio-control/istio-autoinject/templates/service.yaml
  istio-control/istio-autoinject/templates/serviceaccount.yaml
  istio-policy/templates/autoscale.yaml
  istio-policy/templates/deployment.yaml
  istio-policy/templates/poddisruptionbudget.yaml
  istio-policy/templates/service.yaml
  istio-telemetry/mixer-telemetry/templates/autoscale.yaml
  istio-telemetry/mixer-telemetry/templates/deployment.yaml
  istio-telemetry/mixer-telemetry/templates/poddisruptionbudget.yaml
  istio-telemetry/mixer-telemetry/templates/service.yaml
  kustomize/citadel/citadel.yaml
  kustomize/default/istio-autoinject.gen.yaml
  kustomize/default/istio-citadel.gen.yaml
  kustomize/default/istio-ingress.gen.yaml
  kustomize/default/istio-telemetry.gen.yaml
  security/citadel/templates/deployment.yaml
  security/citadel/templates/poddisruptionbudget.yaml
  security/citadel/templates/service.yaml
  security/citadel/templates/serviceaccount.yaml
  test/demo/citadel.gen.yaml
  test/demo/egress.gen.yaml
  test/demo/ingress.gen.yaml
  test/demo/inject-allns.gen.yaml
  test/demo/policy.gen.yaml
  test/demo/telemetry.gen.yaml
Labels: cherrypick/release-1.4, cla: yes, size/M

#540 [release-1.4] Sync labels with istio/istio
  gateways/istio-egress/templates/autoscale.yaml
  gateways/istio-egress/templates/service.yaml
  gateways/istio-ingress/templates/autoscale.yaml
  gateways/istio-ingress/templates/service.yaml
  istio-control/istio-autoinject/templates/deployment.yaml
  istio-control/istio-autoinject/templates/service.yaml
  istio-control/istio-autoinject/templates/serviceaccount.yaml
  istio-policy/templates/autoscale.yaml
  istio-policy/templates/deployment.yaml
  istio-policy/templates/poddisruptionbudget.yaml
  istio-policy/templates/service.yaml
  istio-telemetry/mixer-telemetry/templates/autoscale.yaml
  istio-telemetry/mixer-telemetry/templates/deployment.yaml
  istio-telemetry/mixer-telemetry/templates/poddisruptionbudget.yaml
  istio-telemetry/mixer-telemetry/templates/service.yaml
  kustomize/citadel/citadel.yaml
  kustomize/cluster/gen-crds-namespace.yaml
  kustomize/default/gen-istio-autoinject.yaml
  kustomize/default/gen-istio-citadel.yaml
  kustomize/default/gen-istio-ingress.yaml
  kustomize/default/gen-istio-telemetry.yaml
  security/citadel/templates/deployment.yaml
  security/citadel/templates/poddisruptionbudget.yaml
  security/citadel/templates/service.yaml
  security/citadel/templates/serviceaccount.yaml
  test/demo/gen-citadel.yaml
  test/demo/gen-egress.yaml
  test/demo/gen-ingress.yaml
  test/demo/gen-inject-allns.yaml
  test/demo/gen-policy.yaml
  test/demo/gen-telemetry.yaml
Labels: cla: yes, size/L

#541 update for telemetryv2
  istio-control/istio-discovery/templates/configmap.yaml
  kustomize/default/istio-discovery.gen.yaml
  kustomize/istio-canary/discovery.gen.yaml
  kustomize/minimal/discovery.gen.yaml
  test/demo/pilot.gen.yaml
Labels: cla: yes, size/XS

#543 Add the port number back for meshexpansion-vs-pilot
  gateways/istio-ingress/templates/meshexpansion.yaml
Labels: cherrypick/release-1.4, cla: yes, size/XS

#544 [release-1.4] Add the port number back for meshexpansion-vs-pilot
  gateways/istio-ingress/templates/meshexpansion.yaml
Labels: cla: yes, size/XS

#550 Move telemetry v2 values
  istio-control/istio-discovery/templates/configmap.yaml
  istio-control/istio-discovery/templates/telemetryv2.yaml
  istio-control/istio-discovery/values.yaml
Labels: cla: yes, size/S

#549 Move telemetry v2 values to telemetry.v2
  istio-control/istio-discovery/templates/configmap.yaml
  istio-control/istio-discovery/templates/telemetryv2.yaml
  istio-control/istio-discovery/values.yaml
  kustomize/default/istio-discovery.gen.yaml
  kustomize/istio-canary/discovery.gen.yaml
  kustomize/minimal/discovery.gen.yaml
  test/demo/pilot.gen.yaml
  test/demo/values.yaml
Labels: cla: yes, size/S

#551 Telemetry v2 off by default
  istio-control/istio-discovery/values.yaml
  kustomize/default/istio-discovery.gen.yaml
  kustomize/istio-canary/discovery.gen.yaml
  kustomize/minimal/discovery.gen.yaml
  test/demo/pilot.gen.yaml
Labels: cla: yes, size/XS

#542 add namespace for envoyfilter.
  global.yaml
  istio-control/istio-discovery/metadata-exchange-v2.yaml
  istio-control/istio-discovery/stats-filter-v2.yaml
  istio-control/istio-discovery/templates/telemetryv2.yaml
  kustomize/default/istio-autoinject.gen.yaml
  kustomize/default/istio-discovery.gen.yaml
  kustomize/istio-canary/discovery.gen.yaml
  kustomize/minimal/discovery.gen.yaml
  test/demo/inject-allns.gen.yaml
  test/demo/pilot.gen.yaml
Labels: cla: yes, size/L

#554 Kill gen
  .gitignore
  Makefile.core.mk
  kustomize/citadel/citadel.yaml
  kustomize/citadel/kustomization.yaml
  kustomize/cluster/crds-namespace.gen.yaml
  kustomize/default/istio-autoinject.gen.yaml
  kustomize/default/istio-citadel.gen.yaml
  kustomize/default/istio-config.gen.yaml
  kustomize/default/istio-discovery.gen.yaml
  kustomize/default/istio-grafana.gen.yaml
  kustomize/default/istio-ingress.gen.yaml
  kustomize/default/istio-prometheus.gen.yaml
  kustomize/default/istio-telemetry.gen.yaml
  kustomize/istio-canary/discovery.gen.yaml
  kustomize/istio-ingress/istio-ingress.gen.yaml
  kustomize/minimal/discovery.gen.yaml
  test/demo/citadel.gen.yaml
  test/demo/egress.gen.yaml
  test/demo/example/kustomization.yaml
  test/demo/galley.gen.yaml
  test/demo/grafana.gen.yaml
  test/demo/ingress.gen.yaml
  test/demo/inject-allns.gen.yaml
  test/demo/kiali.gen.yaml
  test/demo/pilot.gen.yaml
  test/demo/policy.gen.yaml
  test/demo/prometheus.gen.yaml
  test/demo/telemetry.gen.yaml
  test/demo/tracing.gen.yaml
  test/install.mk
  test/knative/istio-ingress.gen.yaml
  test/noauth.mk
Labels: cla: yes, size/L

#555 Update common
  Makefile
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/license-lint.yml
  common/scripts/check_clean_repo.sh
Labels: cla: yes, size/M

#553 Register new RequestAuthentication API
  base/files/crd-all.gen.yaml
Labels: cla: yes, size/XS

#559 Fix empty field value
  istio-control/istio-discovery/values.yaml
  istio-telemetry/grafana/values.yaml
  istio-telemetry/kiali/values.yaml
Labels: cla: yes, size/S

#557 remove egress sds
  gateways/istio-egress/templates/deployment.yaml
  gateways/istio-egress/templates/serviceaccount.yaml
  gateways/istio-egress/values.yaml
Labels: cla: yes, size/M

#562 Fix helm template option in iop
  bin/iop
Labels: cla: yes, ok-to-test, size/XS

#563 tracing: Fix tracing service port
  istio-telemetry/tracing/templates/service.yaml
Labels: cla: yes, size/XS

#564 tracing: Fix tracing service port
  istio-telemetry/tracing/templates/service.yaml
Labels: cla: yes, size/XS

#561 Set stream_idle_timeout for pilot/galley listeners
  istio-control/istio-config/templates/configmap-envoy.yaml
  istio-control/istio-discovery/templates/configmap-envoy.yaml
  istio-telemetry/mixer-telemetry/templates/configmap-envoy.yaml
Labels: cla: yes, ok-to-test, size/XS

#565 [release-1.4] remove duplicate field
  istio-telemetry/mixer-telemetry/templates/config.yaml
  kustomize/default/gen-istio-telemetry.yaml
  test/demo/gen-telemetry.yaml
Labels: cla: yes, size/XS

#566 Support SSE for galley config
  istio-control/istio-config/templates/deployment.yaml
  istio-control/istio-config/values.yaml
  istio-control/istio-discovery/templates/configmap.yaml
  istio-control/istio-discovery/values.yaml
Labels: cla: yes, size/S

#568 Support Kubernetes 1.16 in Grafana
  istio-telemetry/grafana/dashboards/citadel-dashboard.json
  istio-telemetry/grafana/dashboards/galley-dashboard.json
  istio-telemetry/grafana/dashboards/istio-performance-dashboard.json
  istio-telemetry/grafana/dashboards/mixer-dashboard.json
  istio-telemetry/grafana/dashboards/pilot-dashboard.json
Labels: cla: yes, size/L

#569 Update Telemetry v2 config
  istio-control/istio-discovery/templates/telemetryv2.yaml
Labels: cla: yes, size/S

#558 Fix helm flags in readme
  README.md
Labels: cla: yes, ok-to-test, size/XS

#570 add quote for affinity values.
  gateways/istio-egress/templates/_affinity.tpl
  gateways/istio-ingress/templates/_affinity.tpl
  istio-control/istio-autoinject/templates/_affinity.tpl
  istio-control/istio-config/templates/_affinity.tpl
  istio-control/istio-discovery/templates/_affinity.tpl
  istio-policy/templates/_affinity.tpl
  istio-telemetry/grafana/templates/_affinity.tpl
  istio-telemetry/kiali/templates/_affinity.tpl
  istio-telemetry/mixer-telemetry/templates/_affinity.tpl
  istio-telemetry/prometheus-operator/templates/_affinity.tpl
  istio-telemetry/prometheus/templates/_affinity.tpl
  istio-telemetry/tracing/templates/_affinity.tpl
  istiocoredns/templates/_affinity.tpl
  security/certmanager/templates/_affinity.tpl
  security/citadel/templates/_affinity.tpl
  security/nodeagent/templates/_affinity.tpl
Labels: cla: yes, size/L

#572 move env to correct place
  istio-telemetry/mixer-telemetry/templates/deployment.yaml
  istio-telemetry/mixer-telemetry/values.yaml
Labels: cla: yes, size/S

#573 Resolution for a regression
  istio-telemetry/tracing/templates/service.yaml
  istio-telemetry/tracing/values.yaml
Labels: cherrypick/release-1.4, cla: yes, size/XS

#571 add node selector to tracing component.
  istio-telemetry/tracing/templates/_affinity.tpl
Labels: cla: yes, size/XS

#577 Fix DataDog traces are not being sent bug
  istio-control/istio-autoinject/templates/configmap.yaml
Labels: cla: yes, size/XS

#574 [release-1.4] move env to correct place
  istio-telemetry/mixer-telemetry/templates/deployment.yaml
  istio-telemetry/mixer-telemetry/values.yaml
Labels: cla: yes, size/S

#579 [release-1.4] add node selector to tracing component.
  istio-telemetry/tracing/templates/_affinity.tpl
Labels: cla: yes, size/XS

#576 [release-1.4] Resolution for a regression
  istio-telemetry/tracing/templates/service.yaml
  istio-telemetry/tracing/values.yaml
Labels: cla: yes, size/XS

#575 Port CRD changes to installer
  base/files/crd-10.yaml
  base/files/crd-11.yaml
  base/files/crd-14.yaml
Labels: cla: yes, size/L

#580 Add permissions for endpointslices
  istio-control/istio-discovery/templates/clusterrole.yaml
Labels: cla: yes, size/XS
