Repository istio/installer, pull requests merged in 2019-09, with the labels that each got.

#370 Update CODEOWNERS
  CODEOWNERS
Labels: cla: yes, size/XS

#373 fix broken ci.
  Makefile
  test/tests.mk
Labels: cla: yes, size/XS

#371 Add script to check if newlines are missing
  gateways/istio-egress/templates/serviceaccount.yaml
  gateways/istio-ingress/templates/serviceaccount.yaml
  istio-telemetry/grafana/templates/service.yaml
  istio-telemetry/kiali/templates/configmap.yaml
  istio-telemetry/prometheus/templates/inrgess.yaml
  istio-telemetry/tracing/Chart.yaml
  istio-telemetry/tracing/templates/pvc.yaml
  istio-telemetry/tracing/templates/service-jaeger.yaml
  scripts/check_lineending.sh
  security/nodeagent/templates/daemonset.yaml
  test/k8s/etcd.yaml
  test/simple/routingrule1.yaml
  test/simple/routingrule2.yaml
  test/simple/routingruleNoPods.yaml
Labels: cla: yes, size/M

#377 increase protocol detection timeout to 1s
  global.yaml
Labels: cherrypick/release-1.3, cla: yes, size/XS

#369 Update dockerfile
  .circleci/config.yml
  Makefile
  test/docker/Dockerfile
Labels: cla: yes, size/XS

#378 Add label name to namespaces
  bin/iop
Labels: cla: yes, size/XS

#380 Add milliseconds duration to dashboard
  istio-telemetry/grafana/dashboards/istio-mesh-dashboard.json
  istio-telemetry/grafana/dashboards/istio-service-dashboard.json
  istio-telemetry/grafana/dashboards/istio-workload-dashboard.json
Labels: cherrypick/release-1.3, cla: yes, size/M

#385 [release-1.3] Add milliseconds duration to dashboard
  istio-telemetry/grafana/dashboards/istio-mesh-dashboard.json
  istio-telemetry/grafana/dashboards/istio-service-dashboard.json
  istio-telemetry/grafana/dashboards/istio-workload-dashboard.json
Labels: cla: yes, size/M

#379 Update common files.
  .commonfiles.sha
  .gitattributes
  Makefile
  Makefile.core.mk
  Makefile.overrides.mk
  SUPPORT.md
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/.golangci.yml
  common/config/.hadolint.yml
  common/config/.yamllint.yml
  common/config/mdl.rb
  common/config/sass-lint.yml
  common/config/tslint.json
  common/scripts/gobuild.sh
  common/scripts/lint_copyright_banner.sh
  common/scripts/lint_go.sh
  common/scripts/report_build_info.sh
Labels: cla: yes, size/XXL

#390 Add a lint_modern target.
  .concourse/set-pipeline.sh
  Makefile.core.mk
  bin/cleanup.sh
  bin/env.sh
  bin/report.sh
  common/.commonfiles.sha
  common/Makefile.common.mk
  test/buildkite/install-gcp.sh
  test/buildkite/run-local.sh
Labels: cla: yes, size/M

#375 remove prometheusNamespace in kaili
  istio-telemetry/kiali/values.yaml
Labels: cla: yes, size/XS

#389 Delete some dead scripts.
  scripts/check_license.sh
  scripts/check_lineending.sh
  scripts/run_gofmt.sh
  scripts/run_golangci.sh
Labels: cla: yes, size/L

#392 Enable more linters on this repo.
  Makefile
  Makefile.core.mk
  README.md
  common/.commonfiles.sha
  common/Makefile.common.mk
  docs/labels.md
  istio-control/istio-config/README.md
  kustomize/README.md
  test/buildkite/README.md
Labels: cla: yes, size/L

#394 remove legacy config checksum.
  istio-control/istio-discovery/templates/_helpers.tpl
  istio-control/istio-discovery/templates/deployment.yaml
Labels: cla: yes, size/XS

#372 Make envoy configMap optional
  istio-control/istio-config/templates/configmap-envoy.yaml
  istio-control/istio-config/templates/configmap-mesh.yaml
  istio-control/istio-config/templates/deployment.yaml
Labels: cla: yes, size/XS

#376 Correct Kiali Annotation in values.yaml
  istio-telemetry/kiali/values.yaml
Labels: cla: yes, size/XS

#391 Kill integration tests
  .circleci/config.yml
Labels: cla: yes, size/M

#393 capitalize env vars.
  security/nodeagent/templates/daemonset.yaml
  security/nodeagent/values.yaml
Labels: cla: yes, size/XS

#395 Make use of apps/v1 instead of deprecated extensions
  istio-cni/templates/daemonset.yaml
  istio-telemetry/prometheus/templates/ingress.yaml
Labels: cla: yes, size/XS

#382 Correct prometheus configurations
  README.md
  istio-telemetry/prometheus/templates/configmap.yaml
Labels: cla: yes, size/S

#383 Correct telemetry installation
  README.md
  istio-control/istio-discovery/templates/configmap.yaml
Labels: cla: yes, size/S

#360 Simplify mixer destination rules
  istio-policy/templates/config.yaml
  istio-telemetry/mixer-telemetry/templates/config.yaml
Labels: cla: yes, size/S

#387 add missing pod annotations parameter to istio charts.
  istio-cni/templates/daemonset.yaml
  istio-cni/values.yaml
  istio-control/istio-autoinject/templates/deployment.yaml
  istio-control/istio-autoinject/values.yaml
  istio-control/istio-config/templates/deployment.yaml
  istio-control/istio-config/values.yaml
  istio-control/istio-discovery/templates/deployment.yaml
  istio-control/istio-discovery/values.yaml
  istio-telemetry/grafana/templates/deployment.yaml
  istio-telemetry/grafana/values.yaml
  istio-telemetry/kiali/templates/deployment.yaml
  istio-telemetry/kiali/values.yaml
  istio-telemetry/mixer-telemetry/values.yaml
  istio-telemetry/prometheus/templates/deployment.yaml
  istio-telemetry/prometheus/values.yaml
  istio-telemetry/tracing/templates/deployment-jaeger.yaml
  istio-telemetry/tracing/templates/deployment-opencensus.yaml
  istio-telemetry/tracing/templates/deployment-zipkin.yaml
  istio-telemetry/tracing/values.yaml
  istiocoredns/templates/deployment.yaml
  istiocoredns/values.yaml
  security/certmanager/values.yaml
  security/citadel/templates/deployment.yaml
  security/citadel/values.yaml
  security/nodeagent/templates/daemonset.yaml
  security/nodeagent/values.yaml
Labels: cla: yes, size/M

#384 Upgrade Kiali to support configure istio_component_namespaces
  README.md
  istio-telemetry/kiali/templates/clusterrole.yaml
  istio-telemetry/kiali/templates/configmap.yaml
  istio-telemetry/kiali/values.yaml
Labels: cla: yes, size/L

#400 Add helm option to set enableAutoMtls
  global.yaml
  istio-control/istio-discovery/templates/configmap.yaml
Labels: cla: yes, size/S

#401 Correct CoreDNS config and prevent race condition
  istiocoredns/templates/configmap.yaml
Labels: cla: yes, size/XS

#402 Fixed the CNI_ARGS for GKE clusters
  README.md
Labels: cla: yes, ok-to-test, size/XS

#399 Make tracing.service.type work
  istio-telemetry/tracing/templates/service.yaml
  istio-telemetry/tracing/values.yaml
Labels: cla: yes, ok-to-test, size/S

#403 injector: update datadog config in template
  istio-control/istio-autoinject/files/injection-template.yaml
Labels: cherrypick/release-1.3, cla: yes, size/XS

#374 Remove unnecessary defaults
  gateways/istio-egress/templates/deployment.yaml
  gateways/istio-egress/templates/poddisruptionbudget.yaml
  gateways/istio-ingress/templates/deployment.yaml
  istio-control/istio-autoinject/templates/deployment.yaml
  istio-control/istio-discovery/templates/deployment.yaml
  istio-policy/templates/autoscale.yaml
  istio-policy/templates/deployment.yaml
Labels: cla: yes, size/S

#404 [release-1.3] injector: update datadog config in template
  istio-control/istio-autoinject/files/injection-template.yaml
Labels: cla: yes, size/XS

#409 Enable Cleanup
  .circleci/config.yml
  test/tests.mk
Labels: cla: yes, size/S

#406 Support galley and autoinject run as nonroot
  istio-control/istio-autoinject/templates/deployment.yaml
  istio-control/istio-config/templates/deployment.yaml
Labels: cla: yes, size/S

#410 Run in minikube instead of kind
  .circleci/config.yml
  bin/testEnvRootMinikube.sh
Labels: cla: yes, size/S

#408 Migrating https://github.com/istio/istio/pull/17423
  crds/files/crd-10.yaml
  crds/files/crd-11.yaml
  crds/files/crd-12.yaml
  crds/files/crd-14.yaml
  istio-control/istio-config/templates/clusterrole.yaml
Labels: cla: yes, size/L

#413 Use goproxy
  .circleci/config.yml
  Makefile.core.mk
Labels: cla: yes, size/XS

#412 Support distroless docker images
  istio-control/istio-autoinject/files/injection-template.yaml
  kustomize/default/gen-istio-autoinject.yaml
  test/demo/gen-inject-allns.yaml
Labels: cla: yes, size/XS

#414 Update common files.
  Makefile
  Makefile.core.mk
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/.golangci.yml
  common/config/license-lint.yml
  common/scripts/gobuild.sh
  common/scripts/lint_go.sh
  common/scripts/report_build_info.sh
Labels: cla: yes, size/L
