Repository istio/installer, pull requests merged in 2019-12, with the labels that each got.

#581 Add scrape target for istio-sidecar-injector
  istio-telemetry/prometheus-operator/templates/servicemonitors.yaml
  istio-telemetry/prometheus/templates/configmap.yaml
Labels: cla: yes, size/S

#582 Add cluster domain for policy and telemetry
  istio-control/istio-discovery/templates/configmap.yaml
  istio-telemetry/mixer-telemetry/templates/configmap-envoy.yaml
Labels: cherrypick/release-1.4, cla: yes, size/S

#583 [release-1.4] Add cluster domain for policy and telemetry
  istio-control/istio-discovery/templates/configmap.yaml
  istio-telemetry/mixer-telemetry/templates/configmap-envoy.yaml
Labels: cla: yes, size/S

#578 more granular stackdriver control with logging.enabled and metrics.enabled flags
  istio-telemetry/mixer-telemetry/templates/stackdriver.yaml
  istio-telemetry/mixer-telemetry/values.yaml
Labels: cla: yes, size/S

#585 Fix POD_PORTS when multiple containers
  istio-control/istio-autoinject/files/injection-template.yaml
Labels: cherrypick/release-1.4, cla: yes, size/XS

#589 Add protocol detection timeout to mesh config
  istio-control/istio-discovery/templates/configmap.yaml
Labels: cherrypick/release-1.4, cla: yes, size/S

#560 Added jaeger-collector-headless service
  istio-telemetry/tracing/templates/service-jaeger.yaml
Labels: cla: yes, ok-to-test, size/S

#593 Fix extra space in template
  gateways/istio-ingress/templates/preconfigured.yaml
Labels: cla: yes, size/XS

#586 [release-1.4] Fix POD_PORTS when multiple containers
  istio-control/istio-autoinject/files/injection-template.yaml
Labels: cla: yes, size/XS

#591 [release-1.4] update telemetryv2 templates
  global.yaml
  istio-control/istio-discovery/metadata-exchange-v2.yaml
  istio-control/istio-discovery/stats-filter-v2.yaml
  istio-control/istio-discovery/templates/telemetryv2.yaml
  istio-control/istio-discovery/templates/telemetryv2_1.4.yaml
  istio-control/istio-discovery/values.yaml
  test/noauth.mk
Labels: cla: yes, size/L

#590 add stackdriver envoyfilter for telemetryv2
  istio-control/istio-discovery/templates/telemetryv2.yaml
  istio-control/istio-discovery/templates/telemetryv2_1.4.yaml
  istio-control/istio-discovery/templates/telemetryv2_1.5.yaml
  istio-control/istio-discovery/values.yaml
  test/noauth.mk
Labels: cla: yes, size/XL

#594 fix pdb selector.
  istio-policy/templates/poddisruptionbudget.yaml
  istio-telemetry/mixer-telemetry/templates/poddisruptionbudget.yaml
Labels: cherrypick/release-1.4, cla: yes, size/XS

#595 [release-1.4] fix pdb selector.
  istio-policy/templates/poddisruptionbudget.yaml
  istio-telemetry/mixer-telemetry/templates/poddisruptionbudget.yaml
Labels: cla: yes, size/XS

#596 Fixes for mixer mesh config
  istio-control/istio-discovery/templates/configmap.yaml
  istio-control/istio-discovery/values.yaml
Labels: cherrypick/release-1.4, cla: yes, size/S

#597 Fixes for mixer mesh config (#596)
  istio-control/istio-discovery/templates/configmap.yaml
  istio-control/istio-discovery/values.yaml
Labels: cla: yes, size/S

#598 Using SDS, gateways' Citadel secret volume mount should be avoided.
  gateways/istio-egress/templates/deployment.yaml
  gateways/istio-ingress/templates/deployment.yaml
Labels: cla: yes, size/S

#599 Update the owner refs of validatingwebhookconfiguration from namespace to clusterrole
  istio-control/istio-config/templates/clusterrole.yaml
Labels: cla: yes, size/XS

#600 Fixthe SDS issue introduced by #598.
  gateways/istio-ingress/templates/deployment.yaml
Labels: cla: yes, size/XS

#602 [release-1.4] Update the owner refs of validatingwebhookconfiguration from namespace to clusterrole
  istio-control/istio-config/templates/clusterrole.yaml
Labels: cla: yes, size/XS

#603 fix(templates): Correct OWNER urls.
  gateways/istio-egress/templates/deployment.yaml
  gateways/istio-ingress/templates/deployment.yaml
  istio-control/istio-autoinject/files/injection-template.yaml
Labels: cherrypick/release-1.4, cla: yes, size/XS

#604 [release-1.4] fix(templates): Correct OWNER urls.
  gateways/istio-egress/templates/deployment.yaml
  gateways/istio-ingress/templates/deployment.yaml
  istio-control/istio-autoinject/files/injection-template.yaml
Labels: cla: yes, size/XS

#605 Allow set lifecycle to sidecar template
  istio-control/istio-autoinject/files/injection-template.yaml
  istio-control/istio-autoinject/values.yaml
Labels: cla: yes, ok-to-test, size/XS

#607 clean-up validatingwebhookconfiguration
  istio-control/istio-config/templates/validatingwebhookconfiguration.yaml.tpl
Labels: cla: yes, size/M

#608 Sync mesh config map with master
  istio-control/istio-discovery/templates/configmap.yaml
  istio-control/istio-discovery/values.yaml
Labels: cla: yes, size/S

#609 Backport: #605 Allow set lifecycle to sidecar template
  istio-control/istio-autoinject/files/injection-template.yaml
  istio-control/istio-autoinject/values.yaml
Labels: cla: yes, ok-to-test, size/XS

#610 Fix webhook config
  istio-control/istio-config/templates/validatingwebhookconfiguration.yaml.tpl
Labels: cla: yes, size/XS

#614 [release-1.4] Add protocol detection timeout to mesh config
  istio-control/istio-discovery/templates/configmap.yaml
Labels: cla: yes, size/S

#615 add accesslog related settings
  istio-control/istio-discovery/templates/configmap.yaml
Labels: cherrypick/release-1.4, cla: yes

#616 [release-1.4] add accesslog related settings
  istio-control/istio-discovery/templates/configmap.yaml
Labels: cla: yes, size/XS

#619 Update telemetry addon versions
  istio-telemetry/grafana/values.yaml
  istio-telemetry/prometheus-operator/values.yaml
  istio-telemetry/prometheus/values.yaml
Labels: cla: yes, size/XS

#618 Add missing auto-mtls env var
  gateways/istio-egress/templates/deployment.yaml
  gateways/istio-ingress/templates/deployment.yaml
  test/install.mk
  test/minimal/disable-automtls.yaml
  test/minimal/kustomization.yaml
Labels: cla: yes, size/S

#621 Not limit to the owned namespace
  test/k8s/sidecar-local.yaml
Labels: cla: yes, size/XS

#617 add default tolerations support.
  gateways/istio-egress/templates/deployment.yaml
  gateways/istio-ingress/templates/deployment.yaml
  global.yaml
  istio-control/istio-autoinject/templates/deployment.yaml
  istio-control/istio-config/templates/deployment.yaml
  istio-control/istio-discovery/templates/deployment.yaml
  istio-policy/templates/deployment.yaml
  istio-telemetry/grafana/templates/deployment.yaml
  istio-telemetry/kiali/templates/deployment.yaml
  istio-telemetry/kiali/values.yaml
  istio-telemetry/mixer-telemetry/templates/deployment.yaml
  istio-telemetry/prometheus/templates/deployment.yaml
  istio-telemetry/tracing/templates/deployment-jaeger.yaml
  istio-telemetry/tracing/templates/deployment-opencensus.yaml
  istio-telemetry/tracing/templates/deployment-zipkin.yaml
  istio-telemetry/tracing/values.yaml
  istiocoredns/templates/deployment.yaml
  security/certmanager/templates/deployment.yaml
  security/citadel/templates/deployment.yaml
  security/nodeagent/templates/daemonset.yaml
Labels: cla: yes, size/M

#567 Fix for disablePolicyCheck
  istio-control/istio-discovery/templates/configmap.yaml
  test/demo/allocation.yaml
  test/demo/values.yaml
Labels: cherrypick/release-1.4, cla: yes, size/S

#623 Remove duplicated policyCheckFailOpen and consolidate disablePolicyCh…
  istio-control/istio-discovery/templates/configmap.yaml
Labels: cla: yes, size/S

#627 Update prom to 2.15.1
  istio-telemetry/prometheus-operator/values.yaml
  istio-telemetry/prometheus/values.yaml
Labels: cla: yes, size/XS

#624 [release-1.4] Not limit to the owned namespace
  test/k8s/sidecar-local.yaml
Labels: cla: yes, size/XS

#628 Add all securityContext fields in injected containers
  istio-control/istio-autoinject/files/injection-template.yaml
  istio-control/istio-discovery/files/injection-template.yaml
Labels: cherrypick/release-1.3, cherrypick/release-1.4, cla: yes, size/M

#629 [release-1.4] Add all securityContext fields in injected containers
  istio-control/istio-autoinject/files/injection-template.yaml
Labels: cherrypick/release-1.3, cla: yes, size/M

#622 [release-1.4] Fix for disablePolicyCheck
  istio-control/istio-discovery/templates/configmap.yaml
  test/demo/allocation.yaml
  test/demo/values.yaml
Labels: cla: yes, size/S
