Repository istio/installer, pull requests merged in 2019-06, with the labels that each got.

#223 Revert "remove pdb for cert-manager."
  security/certmanager/templates/poddisruptionbudget.yaml
Labels: action/merge-to-release-branch, cla: yes

#226 added batch reporting parameters as helm variables
  istio-control/istio-discovery/templates/configmap.yaml
  istio-control/istio-discovery/values.yaml
Labels: cla: yes

#227 Fix concourse pipeline (istio-ingressgateway naming).
  bin/install.sh
Labels: cla: yes

#225 Update the gateway configs for telemetry add-ons
  gateways/istio-ingress/templates/addongateway.yaml
  gateways/istio-ingress/values.yaml
  istio-telemetry/grafana/templates/ingress.yaml
Labels: cla: yes

#232 Use kustomize for installer concourse pipeline
  .concourse/concourse.yaml
  Makefile
  bin/install.sh
Labels: cla: no

#231 Make sidecar injector clusterrole more restrictive by specifying resourcenames
  istio-control/istio-autoinject/templates/clusterrole.yaml
Labels: cla: yes

#238 Update common files.
  .commonfiles.sha
  .golangci.yml
  BUGS-AND-FEATURE-REQUESTS.md
  LICENSE
  Makefile.common.mk
  scripts/check_license.sh
  scripts/run_gofmt.sh
  scripts/run_golangci.sh
Labels: cla: yes

#240 mount directory instead of file to detect file change
  gateways/istio-egress/templates/deployment.yaml
  gateways/istio-ingress/templates/deployment.yaml
  istio-control/istio-autoinject/files/injection-template.yaml
  istio-control/istio-discovery/templates/deployment.yaml
  istio-policy/templates/deployment.yaml
  istio-telemetry/mixer-telemetry/templates/deployment.yaml
  kustomize/istio-control/istio-autoinject.yaml
  kustomize/istio-telemetry/istio-grafana.yaml
  test/demo/k8s.yaml
Labels: cla: yes

#249 use istio-system for istioNamespace and systemNamespace
  test/tests.mk
Labels: cla: yes

#237 Remove presubmit label
  istio-control/istio-config/templates/validatingwebhookconfiguration.yaml.tpl
  test/tests.mk
Labels: cla: yes

#254 cherrypick #15079 to installer
  security/nodeagent/templates/daemonset.yaml
Labels: cla: yes

#256 Fix sample instructions for security and gateways
  README.md
Labels: cla: yes

#233 Pull request validation pipeline
  .concourse/concourse.yaml
Labels: cla: yes

#257 Update SDS in config map
  istio-control/istio-discovery/templates/configmap.yaml
Labels: cla: yes

#248 Update the clusterrole for citadel
  security/citadel/templates/clusterrole.yaml
Labels: cla: yes

#260 Fix noauth test flakes
  test/noauth.mk
Labels: cla: yes

#261 Changes needed to get integration tests passing
  Makefile
  global.yaml
  istio-control/istio-discovery/templates/configmap.yaml
  kustomize/citadel/citadel.yaml
  kustomize/istio-control/discovery/discovery.yaml
  kustomize/istio-control/istio-autoinject.yaml
  kustomize/istio-control/istio-config.yaml
  kustomize/istio-ingress/istio-ingress.yaml
  kustomize/istio-telemetry/istio-grafana.yaml
  kustomize/istio-telemetry/mixer-telemetry.yaml
  kustomize/micro/discovery.yaml
  kustomize/micro/istio-ingress.yaml
  test/demo/k8s.yaml
  test/tests.mk
Labels: cla: yes

#245 multiple instances support and pdb enabled for citadel.
  security/citadel/templates/deployment.yaml
  security/citadel/templates/poddisruptionbudget.yaml
  security/citadel/values.yaml
Labels: cla: yes

#259 Fix sidecarInjectorWebhook.enableNamespacesByDefault in README
  README.md
Labels: cla: yes

#241 Use strict version for zipkin
  istio-telemetry/tracing/values.yaml
Labels: cla: yes
