Repository istio/installer, pull requests merged in 2019-07, with the labels that each got.

#262 Turn on namespaces by default
  .circleci/config.yml
Labels: cla: yes

#264 cherrypick removing hardcoded istio-system
  security/nodeagent/templates/daemonset.yaml
Labels: cla: yes

#272 Fixed: pod cannot direct traffic to itself via a service
  bin/testEnvRootMinikube.sh
Labels: cla: yes

#270 General readme cleanup
  README.md
Labels: cla: yes

#266 Added --log_as_json container arg to all istio components
  gateways/istio-egress/templates/deployment.yaml
  gateways/istio-ingress/templates/deployment.yaml
  global.yaml
  istio-control/istio-autoinject/files/injection-template.yaml
  istio-control/istio-autoinject/templates/deployment.yaml
  istio-control/istio-config/templates/deployment.yaml
  istio-control/istio-discovery/templates/deployment.yaml
  istio-policy/templates/deployment.yaml
  istio-telemetry/mixer-telemetry/templates/deployment.yaml
  kustomize/istio-control/istio-autoinject.yaml
  security/citadel/templates/deployment.yaml
  security/nodeagent/templates/daemonset.yaml
Labels: cla: yes

#273 Remove extra sds entry
  gateways/istio-ingress/values.yaml
Labels: cla: yes

#274 Add missing namespaces permissions for Galley
  istio-control/istio-config/templates/clusterrole.yaml
  kustomize/istio-control/istio-config.yaml
Labels: cla: yes

#269 specify enable namespaces by default in demo
  kustomize/citadel/namespace.yaml
  test/demo.mk
  test/demo/k8s.yaml
  test/demo/namespace.yaml
  test/install.mk
Labels: cla: yes

#263 Migrate to apps/v1
  kustomize/micro/allocation.yaml
  security/citadel/templates/deployment.yaml
  test/k8s/etcd.yaml
  test/k8s/loadgen.yaml
Labels: cla: yes

#234 Use global imagePullPolicy
  gateways/istio-egress/templates/deployment.yaml
  gateways/istio-ingress/templates/deployment.yaml
  istio-control/istio-autoinject/files/injection-template.yaml
  istio-control/istio-autoinject/templates/deployment.yaml
  istio-control/istio-config/templates/deployment.yaml
  istio-control/istio-discovery/templates/deployment.yaml
  istio-policy/templates/deployment.yaml
  istio-telemetry/grafana/templates/deployment.yaml
  istio-telemetry/kiali/templates/deployment.yaml
  istio-telemetry/mixer-telemetry/templates/deployment.yaml
  istio-telemetry/prometheus/templates/deployment.yaml
  istio-telemetry/tracing/templates/deployment-jaeger.yaml
  istio-telemetry/tracing/templates/deployment-zipkin.yaml
  istiocoredns/templates/deployment.yaml
  security/certmanager/templates/deployment.yaml
  security/citadel/templates/deployment.yaml
  security/nodeagent/templates/daemonset.yaml
Labels: cla: yes

#275 fix missing crds for certmanager.
  crds/templates/crds.yaml
Labels: cla: yes

#276 Wait for all prometheus operator CRDs
  test/install.mk
Labels: cla: yes

#265 Update builder to kind v0.4.0
  .circleci/config.yml
  Makefile
  test/docker/Dockerfile
Labels: cla: yes

#146 Update inject-template.yaml
  istio-control/istio-autoinject/files/injection-template.yaml
Labels: cla: yes

#278 Add missing divider in tracing chart
  istio-telemetry/tracing/templates/service.yaml
Labels: cla: yes

#280 feat(tracing): add alpha support for opencensus service
  istio-telemetry/tracing/templates/deployment-opencensus.yaml
  istio-telemetry/tracing/templates/service.yaml
  istio-telemetry/tracing/values.yaml
Labels: cla: yes

#277 add dns certs for pilot in dual control plane.
  security/citadel/values.yaml
Labels: cla: yes

#282 fix typo in README
  README.md
Labels: cla: yes, size/XS

#279 Make demo directly install citadel
  security/citadel/templates/deployment.yaml
  test/demo/k8s.yaml
  test/demo/kustomization.yaml
  test/demo/namespace.yaml
  test/demo/values.yaml
  test/install.mk
Labels: cla: yes

#284 Sync charts with istio/operator
  crds/templates/namespaces.yaml
  istio-control/istio-config/templates/clusterrole.yaml
  istio-control/istio-config/templates/clusterrolebinding.yaml
  istio-control/istio-config/templates/configmap-envoy.yaml
  istio-control/istio-config/templates/configmap-mesh.yaml
  istio-control/istio-config/templates/configmap.yaml
  istio-control/istio-config/templates/deployment.yaml
  istio-control/istio-config/templates/poddisruptionbudget.yaml
  istio-control/istio-config/templates/service.yaml
  istio-control/istio-config/templates/serviceaccount.yaml
  istio-control/istio-config/templates/validatingwebhookconfiguration.yaml.tpl
  istio-control/istio-discovery/templates/clusterrole.yaml
  istio-control/istio-discovery/templates/clusterrolebinding.yaml
  istio-control/istio-discovery/templates/configmap-envoy.yaml
  istio-control/istio-discovery/templates/configmap.yaml
  istio-control/istio-discovery/templates/deployment.yaml
  istio-control/istio-discovery/templates/enable-mesh-mtls.yaml
  istio-control/istio-discovery/templates/poddisruptionbudget.yaml
  istio-control/istio-discovery/templates/service.yaml
  istio-control/istio-discovery/templates/serviceaccount.yaml
  istio-policy/templates/clusterrole.yaml
  istio-policy/templates/clusterrolebinding.yaml
  istio-policy/templates/config.yaml
  istio-policy/templates/deployment.yaml
  istio-policy/templates/poddisruptionbudget.yaml
  istio-policy/templates/serviceaccount.yaml
  istio-telemetry/mixer-telemetry/templates/clusterrole.yaml
  istio-telemetry/mixer-telemetry/templates/clusterrolebinding.yaml
  istio-telemetry/mixer-telemetry/templates/configmap-envoy.yaml
  istio-telemetry/mixer-telemetry/templates/deployment.yaml
  istio-telemetry/mixer-telemetry/templates/poddisruptionbudget.yaml
  istio-telemetry/mixer-telemetry/templates/service.yaml
  istio-telemetry/mixer-telemetry/templates/serviceaccount.yaml
Labels: cla: yes, size/L

#286 Add manually generated istio.yaml for 1.2(.2)
  kustomize/istio-1.1/kustomization.yaml
  kustomize/istio-1.2/default/istio.yaml
  kustomize/istio-1.2/default/kustomization.yaml
  kustomize/istio-1.2/default/namespace.yaml
  kustomize/istio-1.2/default/values.yaml
  kustomize/istio-1.2/minimal/istio.yaml
  kustomize/istio-1.2/minimal/kustomization.yaml
  kustomize/istio-1.2/minimal/namespace.yaml
  kustomize/istio-1.2/minimal/values-istio-minimal.yaml
Labels: cla: yes, size/XXL

#287 Add sidecars for kiali
  istio-telemetry/kiali/templates/clusterrole.yaml
Labels: cla: yes, size/XS

#267 Pass enableNamespacesByDefault to istio config
  .circleci/config.yml
  Makefile
  test/install.mk
  test/tests.mk
Labels: cla: yes, size/S

#288 Small fixes and updates from master.
  istio-control/istio-autoinject/files/injection-template.yaml
  istio-control/istio-autoinject/templates/deployment.yaml
  kustomize/istio-1.2/default/kustomization.yaml
  security/citadel/templates/deployment.yaml
  security/citadel/templates/service.yaml
Labels: cla: yes, size/M

#285 Update versions field in crds definition.
  crds/files/crd-10.yaml
  crds/files/crd-11.yaml
  crds/files/crd-12.yaml
  crds/files/crd-certmanager-10.yaml
  crds/files/crd-certmanager-11.yaml
Labels: cla: yes, needs-ok-to-test, size/L

#292 Upgrade kaili to v1.1.0
  istio-telemetry/kiali/Chart.yaml
  istio-telemetry/kiali/templates/configmap.yaml
  istio-telemetry/kiali/templates/deployment.yaml
  istio-telemetry/kiali/values.yaml
Labels: cla: yes, size/M

#294 Disable failing minikube test
  .mergify.yml
Labels: cla: yes, size/XS

#298 fix ingress-gateway rolebinding labels
  gateways/istio-ingress/templates/rolebindings.yaml
Labels: cla: yes, needs-ok-to-test, size/XS

#296 Fix typo error
  README.md
Labels: cla: yes, size/XS

#297 Delete validatingwebhookconfiguration if configValidation=false
  istio-control/istio-config/templates/configmap.yaml
  istio-control/istio-config/templates/validatingwebhookconfiguration.yaml.tpl
Labels: cla: yes, size/XS

#293 fix istio upgrade issue
  istio-telemetry/kiali/templates/clusterrolebinding.yaml
Labels: cla: yes, size/S

#283 remove namespace for meshpolicy.
  istio-control/istio-discovery/templates/enable-mesh-mtls.yaml
  kustomize/istio-control/discovery/discovery.yaml
  kustomize/micro/discovery.yaml
  test/demo/k8s.yaml
Labels: cla: yes, size/M
