Repository istio/installer, pull requests merged in 2020-02, with the labels that each got.

#654 [release-1.4] Adding cni repair functionality to the istioctl installer.
  istio-cni/templates/clusterrole.yaml
  istio-cni/templates/clusterrolebinding.yaml
  istio-cni/templates/daemonset.yaml
  istio-cni/values.yaml
  istio-control/istio-autoinject/files/injection-template.yaml
Labels: cla: yes, size/L

#655 [release-1.4] Adding flag allow users to disable cni validation init container
  istio-cni/values.yaml
  istio-control/istio-autoinject/files/injection-template.yaml
  istio-control/istio-autoinject/values.yaml
Labels: cla: yes, size/S

#656 Updating installer repo to reflect changes made in helm chart in istio
  istio-control/istio-autoinject/files/injection-template.yaml
Labels: cla: yes, size/S

#657 Remote clusters installed with istioctl are unable to use FQDN for pilot endpoints. (#635)
  istio-control/istio-autoinject/templates/configmap.yaml
Labels: cla: yes, size/S

#660 allow galley to add a finalizer to its own namespace
  istio-control/istio-config/templates/clusterrole.yaml
Labels: cla: yes, size/XS

#658 add mcp message size to galley dashboard
  istio-telemetry/grafana/dashboards/galley-dashboard.json
Labels: cla: yes, size/M

#661 [release-1.4] Manual backport equivalent to istio/istio#20923
  istio-cni/templates/daemonset.yaml
  istio-cni/values.yaml
Labels: cla: yes, size/XS

#662 Remove duplicate sdsudspath volume for egressgateway
  gateways/istio-egress/templates/deployment.yaml
Labels: cla: yes, ok-to-test, size/XS

#663 [Release-1.4] Add stackdriver tracing options to istio/installer (#640)
  global.yaml
  istio-control/istio-autoinject/files/injection-template.yaml
  istio-control/istio-autoinject/templates/configmap.yaml
  istio-control/istio-discovery/templates/configmap.yaml
Labels: cla: yes, size/M
