Repository istio/installer, pull requests merged in 2020-01, with the labels that each got.

#634 Fix metadata exchange filter inline code string
  istio-control/istio-discovery/templates/telemetryv2_1.5.yaml
Labels: cla: yes, size/XS

#633 Fixes for istiod
  bin/env.sh
  gateways/istio-ingress/templates/deployment.yaml
  gateways/istio-ingress/templates/role.yaml
  gateways/istio-ingress/templates/rolebindings.yaml
  istio-control/istio-autoinject/templates/deployment.yaml
  istio-control/istio-autoinject/templates/mutatingwebhook.yaml
  istio-control/istio-discovery/files/injection-template.yaml
  istio-control/istio-discovery/templates/clusterrole.yaml
  istio-control/istio-discovery/templates/clusterrolebinding.yaml
  istio-control/istio-discovery/templates/configmap.yaml
  istio-control/istio-discovery/templates/deployment.yaml
  istio-control/istio-discovery/templates/service.yaml
  istio-telemetry/prometheus-operator/templates/servicemonitors.yaml
  istio-telemetry/prometheus-operator/values.yaml
  istio-telemetry/prometheus/templates/configmap.yaml
  istio-telemetry/prometheus/templates/deployment.yaml
  istio-telemetry/prometheus/values.yaml
  kustomize/cluster/istiod.yaml
  test/install.mk
Labels: cla: yes, size/L

#636 Make the CA_ADDR not bound to istio-system.
  istio-control/istio-discovery/files/injection-template.yaml
Labels: cla: yes, size/XS

#635 Remote clusters installed with istioctl are unable to use FQDN for pilot
  istio-control/istio-autoinject/templates/configmap.yaml
Labels: cla: yes, ok-to-test, size/S

#637 xds: use typedstruct
  istio-control/istio-discovery/templates/telemetryv2_1.5.yaml
Labels: cla: yes, size/L

#638 Sync dashboards with istio/istio
  istio-telemetry/grafana/dashboards/citadel-dashboard.json
  istio-telemetry/grafana/dashboards/galley-dashboard.json
  istio-telemetry/grafana/dashboards/istio-mesh-dashboard.json
Labels: cla: yes, size/L

#639 Fixes for istiod injection
  istio-control/istio-autoinject/templates/clusterrole.yaml
  istio-control/istio-autoinject/templates/clusterrolebinding.yaml
  istio-control/istio-autoinject/templates/configmap.yaml
  istio-control/istio-autoinject/templates/deployment.yaml
  istio-control/istio-autoinject/templates/poddisruptionbudget.yaml
  istio-control/istio-autoinject/templates/service.yaml
  istio-control/istio-autoinject/templates/serviceaccount.yaml
  istio-control/istio-autoinject/templates/sidecar-injector-configmap.yaml
  istio-control/istio-discovery/templates/deployment.yaml
  istio-control/istio-discovery/templates/istiod-injector-configmap.yaml
  istio-control/istio-discovery/values.yaml
  test/demo/allocation.yaml
  test/install.mk
Labels: cla: yes, size/M

#640 Add stackdriver tracing options to istio/installer
  global.yaml
  istio-control/istio-autoinject/files/injection-template.yaml
  istio-control/istio-autoinject/templates/configmap.yaml
  istio-control/istio-discovery/files/injection-template.yaml
  istio-control/istio-discovery/templates/configmap.yaml
Labels: cla: yes, size/M

#626 limit cni in kube-system
  README.md
Labels: cla: yes, size/XS

#642 fix duplicate entry of destionarule for multicluster
  gateways/istio-egress/templates/preconfigured.yaml
  gateways/istio-ingress/templates/preconfigured.yaml
Labels: cla: yes, size/XS

#646 [release-1.4] fix duplicate entry of destionarule for multicluster
  gateways/istio-egress/templates/preconfigured.yaml
  gateways/istio-ingress/templates/preconfigured.yaml
Labels: cla: yes, size/XS

#645 Mount Citadel CA cert to data plane and config istiod CA provider
  global.yaml
  istio-control/istio-discovery/files/injection-template.yaml
  istio-control/istio-discovery/templates/deployment.yaml
Labels: cla: yes, size/S

#632 Support customized labels for istio-ingress
  gateways/istio-egress/templates/autoscale.yaml
  gateways/istio-egress/templates/deployment.yaml
  gateways/istio-egress/templates/poddisruptionbudget.yaml
  gateways/istio-egress/templates/preconfigured.yaml
  gateways/istio-egress/templates/service.yaml
  gateways/istio-egress/templates/serviceaccount.yaml
  gateways/istio-egress/values.yaml
  gateways/istio-ingress/templates/autoscale.yaml
  gateways/istio-ingress/templates/deployment.yaml
  gateways/istio-ingress/templates/poddisruptionbudget.yaml
  gateways/istio-ingress/templates/preconfigured.yaml
  gateways/istio-ingress/templates/service.yaml
  gateways/istio-ingress/templates/serviceaccount.yaml
  gateways/istio-ingress/values.yaml
Labels: cla: yes, size/L

#644 Replace envoy_bootstrap with custom_bootstrap
  istio-control/istio-autoinject/files/injection-template.yaml
  istio-control/istio-discovery/files/injection-template.yaml
Labels: cla: yes, size/XS

#630 [release-1.3] Add all securityContext fields in injected containers
  istio-control/istio-autoinject/files/injection-template.yaml
Labels: cla: yes, size/M

#647 Add annotation for enableCoreDump
  istio-control/istio-autoinject/files/injection-template.yaml
Labels: cla: yes, ok-to-test, size/XS

#650 Fix Galley helm template volume mounts
  istio-control/istio-config/templates/deployment.yaml
Labels: cla: yes, size/S

#651 More fix on Galley's configValidation cert mount
  istio-control/istio-config/templates/deployment.yaml
Labels: cla: yes, size/S
